import { z } from 'zod'
import type { FormFieldSchema } from '@/components/forms/useFormBuilder'
import { formSection } from '@/lib/form-standards'
import { PAYMENT_METHOD_OPTIONS } from '@/lib/finance-constants'
import {
  inventoryItemRelation,
  invoiceRelation,
  studentRelation,
  staffUserRelation,
  transportDriverRelation,
  transportVehicleRelation,
  classRelation,
  feeCategoryRelation,
  feeGroupRelation,
  feeStructureRelation,
  studentCategoryRelation,
  designationRelation,
  departmentRelation,
  gradeLevelRelation,
  streamRelation,
  subjectRelation,
  incomeHeadRelation,
  expenseHeadRelation,
} from '@/lib/form-relations'
import { moduleEndpoints } from '@/services'
import { studentFormFields, studentFormSchema } from '@/modules/students/student-form'
import { guardianFormFields, guardianFormSchema } from '@/modules/guardians/guardian-form'
import { leaveFormFields, leaveFormSchema } from '@/modules/hr/leave-form'
import { teacherFormFields, teacherFormSchema } from '@/modules/teachers/teacher-form'

export interface ModuleCrudConfig {
  formFields: FormFieldSchema[]
  formSchema: z.ZodTypeAny
  canCreate?: boolean
  canEdit?: boolean
  canDelete?: boolean
  idKey?: string
  /** Show one section per step until submit (for long multi-section forms). */
  staged?: boolean
}

function crud(
  formFields: FormFieldSchema[],
  formSchema: z.ZodTypeAny,
  options: Partial<ModuleCrudConfig> = {},
): ModuleCrudConfig {
  return {
    canCreate: true,
    canEdit: true,
    canDelete: true,
    formFields,
    formSchema,
    ...options,
  }
}

const statusOptions = [
  { label: 'Present', value: 'present' },
  { label: 'Absent', value: 'absent' },
  { label: 'Late', value: 'late' },
  { label: 'Excused', value: 'excused' },
]

export const moduleCrudRegistry: Record<string, ModuleCrudConfig> = {
  students: crud(studentFormFields, studentFormSchema, { staged: true }),
  teachers: crud(teacherFormFields, teacherFormSchema),
  guardians: crud(guardianFormFields, guardianFormSchema, { canEdit: true, canDelete: true }),
  'academics-setup': crud(
    [
      {
        name: 'grade_level_id',
        label: 'Grade level',
        type: 'relation',
        required: true,
        section: 'Class details',
        placeholder: 'Select grade level',
        description: 'Year level such as Form 4 or Lower 6. This is the academic level for the class.',
        colSpan: 1,
        relation: gradeLevelRelation(),
      },
      {
        name: 'stream_id',
        label: 'Stream',
        type: 'relation',
        section: 'Class details',
        placeholder: 'Optional stream',
        description:
          'Form 1–4: section codes like A, B, A2 (class becomes Form 4A2). Lower/Upper 6: named streams like Commercials or Sciences (class becomes Lower 6 Commercials). Leave empty for Lower/Upper 6 with no stream.',
        colSpan: 1,
        relation: streamRelation(),
      },
      {
        name: 'name',
        label: 'Class name',
        type: 'text',
        required: true,
        section: 'Class details',
        placeholder: 'e.g. Form 4A2 or Lower 6 Commercials',
        description:
          'Built automatically from grade level + stream. You can edit it if your school uses a custom label.',
        colSpan: 1,
        deriveClassName: {
          levelField: 'grade_level_id',
          streamField: 'stream_id',
        },
      },
      {
        name: 'capacity',
        label: 'Capacity',
        type: 'number',
        section: 'Class details',
        placeholder: '40',
        description: 'Maximum learners for this class. Defaults to 40.',
        colSpan: 1,
      },
      {
        name: 'teacher_id',
        label: 'Class teacher',
        type: 'relation',
        section: 'Class details',
        placeholder: 'Select teacher',
        description: 'Optional homeroom / class teacher.',
        colSpan: 1,
        relation: {
          endpoint: moduleEndpoints.teachers,
          moduleLabel: 'teacher',
          createRoute: '/teachers?create=1',
        },
      },
    ],
    z.object({
      name: z.string().trim().min(1, 'Class name is required'),
      capacity: z.preprocess(
        (value) => (value === '' || value == null ? undefined : value),
        z.coerce.number().int().min(1, 'Capacity must be at least 1').optional(),
      ),
      grade_level_id: z.string().min(1, 'Select a grade level'),
      stream_id: z.string().optional().or(z.literal('')),
      teacher_id: z.string().optional().or(z.literal('')),
    }),
  ),
  'academics-streams': crud(
    [
      {
        name: 'name',
        label: 'Stream name',
        type: 'text',
        required: true,
        section: 'Stream',
        colSpan: 1,
        placeholder: 'e.g. A2 or Commercials',
        description: 'Form sections often use short codes (A, B, A2). A-level pathways use names (Commercials, Sciences, Arts).',
      },
      {
        name: 'code',
        label: 'Code',
        type: 'text',
        section: 'Stream',
        colSpan: 1,
        placeholder: 'e.g. A2',
        description: 'Optional short code. For Form classes this is preferred in the class name (Form 4 + A2 → Form 4A2).',
      },
      { name: 'description', label: 'Description', type: 'textarea', section: 'Stream', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox', section: 'Stream', colSpan: 2 },
    ],
    z.object({
      name: z.string().min(1),
      code: z.string().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
    { canDelete: false },
  ),
  'academics-houses': crud(
    [
      { name: 'name', label: 'House name', type: 'text', required: true, section: 'House', colSpan: 1 },
      { name: 'code', label: 'Code', type: 'text', section: 'House', colSpan: 1 },
      { name: 'color', label: 'Colour', type: 'text', section: 'House', colSpan: 1 },
      {
        name: 'teacher_id',
        label: 'House master / mistress',
        type: 'relation',
        section: 'House',
        colSpan: 1,
        relation: { endpoint: moduleEndpoints.teachers },
      },
      { name: 'is_active', label: 'Active', type: 'checkbox', section: 'House', colSpan: 2 },
    ],
    z.object({
      name: z.string().min(1),
      code: z.string().optional(),
      color: z.string().optional(),
      teacher_id: z.string().optional().or(z.literal('')),
      is_active: z.boolean().optional(),
    }),
    { canDelete: false },
  ),
  'academics-subject-packages': crud(
    [
      {
        name: 'grade_level_id',
        label: 'Grade level',
        type: 'relation',
        required: true,
        section: 'Package',
        relation: gradeLevelRelation(),
      },
      {
        name: 'subject_id',
        label: 'Subject',
        type: 'relation',
        required: true,
        section: 'Package',
        relation: subjectRelation(),
      },
      {
        name: 'stream_id',
        label: 'Stream (optional)',
        type: 'relation',
        section: 'Package',
        relation: streamRelation(),
      },
      {
        name: 'is_core',
        label: 'Core subject',
        type: 'select',
        section: 'Package',
        options: [
          { label: 'Core', value: 'true' },
          { label: 'Elective', value: 'false' },
        ],
      },
    ],
    z.object({
      grade_level_id: z.string().min(1),
      subject_id: z.string().min(1),
      stream_id: z.string().optional().or(z.literal('')),
      is_core: z.string().optional(),
    }),
  ),
  'academics-subjects': crud(
    formSection('Subject', [
      { name: 'name', label: 'Subject name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text' },
      { name: 'order', label: 'Display order', type: 'number', description: 'Lower numbers appear first.' },
      {
        name: 'class_id',
        label: 'Class (optional)',
        type: 'relation',
        placeholder: 'Optional — scope to a class',
        relation: classRelation(),
      },
      {
        name: 'teacher_id',
        label: 'Teacher (optional)',
        type: 'relation',
        placeholder: 'Optional — assign a teacher',
        relation: { endpoint: moduleEndpoints.teachers },
      },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      code: z.string().optional(),
      order: z.coerce.number().optional(),
      class_id: z.string().optional().or(z.literal('')),
      teacher_id: z.string().optional().or(z.literal('')),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'academics-departments': crud(
    formSection('Department', [
      { name: 'name', label: 'Department name', type: 'text', required: true, colSpan: 2 },
      { name: 'code', label: 'Code', type: 'text' },
      {
        name: 'head_teacher_id',
        label: 'Department head',
        type: 'relation',
        placeholder: 'Select teacher',
        relation: { endpoint: moduleEndpoints.teachers },
      },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      code: z.string().optional(),
      head_teacher_id: z.string().optional().or(z.literal('')),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'academics-grade-levels': crud(
    formSection('Grade level', [
      { name: 'name', label: 'Grade level', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text' },
      { name: 'order', label: 'Display order', type: 'number', description: 'Lower numbers appear first.' },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      code: z.string().optional(),
      order: z.coerce.number().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'academics-grading-scales': crud(
    formSection('Grading scale', [
      { name: 'grade', label: 'Grade letter', type: 'text', required: true },
      { name: 'min_score', label: 'Min score', type: 'number', required: true },
      { name: 'max_score', label: 'Max score', type: 'number', required: true },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      grade: z.string().min(1),
      min_score: z.coerce.number(),
      max_score: z.coerce.number(),
      description: z.string().optional(),
    }),
  ),
  'academics-rooms': crud(
    formSection('Room details', [
      { name: 'name', label: 'Room name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text' },
      { name: 'type', label: 'Type', type: 'text', placeholder: 'Classroom, Lab, Hall…' },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      code: z.string().optional(),
      type: z.string().optional(),
      capacity: z.coerce.number().optional(),
      location: z.string().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'academics-terms': crud(
    [
      ...formSection('Term details', [
        { name: 'name', label: 'Term name', type: 'text', required: true, placeholder: 'Term 1' },
        {
          name: 'academic_year',
          label: 'Academic year',
          type: 'text',
          required: true,
          placeholder: '2026-2027',
          description: 'Use the school year range, e.g. 2026-2027.',
        },
        { name: 'start_date', label: 'Start date', type: 'date', required: true },
        { name: 'end_date', label: 'End date', type: 'date', required: true },
        {
          name: 'order',
          label: 'Order',
          type: 'number',
          placeholder: '1',
          description: 'Display order within the academic year (1, 2, 3…).',
        },
        {
          name: 'description',
          label: 'Description',
          type: 'textarea',
          colSpan: 2,
          placeholder: 'Optional notes for this term',
        },
      ]),
      {
        name: 'is_current',
        label: 'Current term',
        type: 'checkbox',
        section: 'Status',
        description: 'Makes this the live term and deactivates all other terms.',
      },
      {
        name: 'is_active',
        label: 'Active',
        type: 'checkbox',
        section: 'Status',
        description: 'Usually only the current term is active. Setting current handles this for you.',
      },
    ],
    z
      .object({
        name: z.string().min(1, 'Term name is required'),
        academic_year: z.string().min(4, 'Academic year is required'),
        start_date: z.string().min(1, 'Start date is required'),
        end_date: z.string().min(1, 'End date is required'),
        order: z.coerce.number().int().min(1).optional(),
        description: z.string().optional(),
        is_current: z.boolean().optional(),
        is_active: z.boolean().optional(),
      })
      .refine((v) => !v.start_date || !v.end_date || v.end_date > v.start_date, {
        message: 'End date must be after start date',
        path: ['end_date'],
      }),
    { staged: false },
  ),
  'academics-assignments': crud(
    formSection('Assignment', [
      { name: 'title', label: 'Title', type: 'text', required: true, colSpan: 2 },
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        required: true,
        placeholder: 'Select class',
        relation: classRelation(),
      },
      {
        name: 'subject_id',
        label: 'Subject',
        type: 'relation',
        required: true,
        placeholder: 'Select subject',
        relation: { endpoint: moduleEndpoints.subjects, moduleLabel: 'subject' },
      },
      {
        name: 'teacher_id',
        label: 'Teacher',
        type: 'relation',
        required: true,
        placeholder: 'Select teacher',
        relation: { endpoint: moduleEndpoints.teachers },
      },
      { name: 'due_date', label: 'Due date', type: 'date', required: true },
      { name: 'total_marks', label: 'Total marks', type: 'number', placeholder: '100' },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      title: z.string().min(1),
      class_id: z.string().min(1),
      subject_id: z.string().min(1),
      teacher_id: z.string().min(1),
      due_date: z.string().min(1),
      total_marks: z.coerce.number().optional(),
      description: z.string().optional(),
    }),
  ),
  'academics-tests': crud(
    formSection('Test details', [
      { name: 'name', label: 'Test name', type: 'text', required: true, colSpan: 2 },
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        required: true,
        placeholder: 'Select class',
        relation: classRelation(),
      },
      {
        name: 'subject_id',
        label: 'Subject',
        type: 'relation',
        required: true,
        placeholder: 'Select subject',
        relation: { endpoint: moduleEndpoints.subjects, moduleLabel: 'subject' },
      },
      {
        name: 'teacher_id',
        label: 'Teacher',
        type: 'relation',
        required: true,
        placeholder: 'Select teacher',
        relation: { endpoint: moduleEndpoints.teachers },
      },
      {
        name: 'term_id',
        label: 'Term (optional)',
        type: 'relation',
        placeholder: 'Select term',
        relation: { endpoint: moduleEndpoints.terms },
      },
      { name: 'test_date', label: 'Test date', type: 'date', required: true },
      { name: 'total_marks', label: 'Total marks', type: 'number', required: true, placeholder: '100' },
      { name: 'academic_year', label: 'Academic year', type: 'text', required: true, placeholder: '2026-2027' },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      class_id: z.string().min(1),
      subject_id: z.string().min(1),
      teacher_id: z.string().min(1, 'Select a teacher'),
      term_id: z.string().optional().or(z.literal('')),
      test_date: z.string().min(1, 'Test date is required'),
      total_marks: z.coerce.number().min(0, 'Total marks is required'),
      academic_year: z.string().min(1, 'Academic year is required'),
      description: z.string().optional(),
    }),
  ),
  'academics-teacher-assignments': crud(
    formSection('Assignment', [
      {
        name: 'teacher_id',
        label: 'Teacher',
        type: 'relation',
        required: true,
        placeholder: 'Select teacher',
        relation: { endpoint: moduleEndpoints.teachers },
      },
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        placeholder: 'Select class',
        relation: classRelation(),
      },
      {
        name: 'subject_id',
        label: 'Subject',
        type: 'relation',
        placeholder: 'Select subject',
        relation: { endpoint: moduleEndpoints.subjects, moduleLabel: 'subject' },
      },
      {
        name: 'grade_level_id',
        label: 'Grade level (optional)',
        type: 'relation',
        placeholder: 'Select grade level',
        relation: { endpoint: moduleEndpoints.gradeLevels },
      },
      { name: 'role', label: 'Role', type: 'text', placeholder: 'Class teacher, Subject teacher…' },
      { name: 'is_active', label: 'Active', type: 'checkbox', colSpan: 2 },
    ]),
    z.object({
      teacher_id: z.string().min(1),
      class_id: z.string().optional().or(z.literal('')),
      subject_id: z.string().optional().or(z.literal('')),
      grade_level_id: z.string().optional().or(z.literal('')),
      role: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'academics-attendance': crud(
    formSection('Attendance', [
      {
        name: 'student_id',
        label: 'Student',
        type: 'relation',
        required: true,
        placeholder: 'Select student',
        relation: studentRelation(),
      },
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        placeholder: 'Select class',
        relation: classRelation(),
      },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'status', label: 'Status', type: 'select', required: true, options: statusOptions },
    ]),
    z.object({
      student_id: z.string().min(1),
      class_id: z.string().optional().or(z.literal('')),
      date: z.string().min(1),
      status: z.string().min(1),
    }),
    { canDelete: false },
  ),
  'academics-timetable': crud(
    [
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        required: true,
        placeholder: 'Select class',
        relation: { endpoint: moduleEndpoints.classes, moduleLabel: 'class' },
      },
      {
        name: 'subject_id',
        label: 'Subject',
        type: 'relation',
        required: true,
        placeholder: 'Select subject',
        relation: { endpoint: moduleEndpoints.subjects, moduleLabel: 'subject' },
      },
      {
        name: 'teacher_id',
        label: 'Teacher',
        type: 'relation',
        placeholder: 'Optional — select teacher',
        relation: { endpoint: moduleEndpoints.teachers },
      },
      {
        name: 'room_id',
        label: 'Room',
        type: 'relation',
        placeholder: 'Optional — select room',
        relation: { endpoint: moduleEndpoints.rooms },
      },
      { name: 'day', label: 'Day', type: 'text', required: true, placeholder: 'Monday' },
      { name: 'start_time', label: 'Start', type: 'text', required: true, placeholder: '08:00' },
      { name: 'end_time', label: 'End', type: 'text', required: true, placeholder: '09:00' },
    ],
    z.object({
      class_id: z.string().min(1),
      subject_id: z.string().min(1),
      teacher_id: z.string().optional().or(z.literal('')),
      room_id: z.string().optional().or(z.literal('')),
      day: z.string().min(1),
      start_time: z.string().min(1),
      end_time: z.string().min(1),
    }),
  ),
  'academics-holiday-programs': crud(
    formSection('Program details', [
      { name: 'name', label: 'Program name', type: 'text', required: true },
      { name: 'academic_year', label: 'Academic year', type: 'text', placeholder: '2026-2027' },
      { name: 'start_date', label: 'Start date', type: 'date', required: true },
      { name: 'end_date', label: 'End date', type: 'date', required: true },
      {
        name: 'fee_amount',
        label: 'Fee',
        type: 'number',
        placeholder: '0.00',
        description: 'Charged in the school fees currency (Settings → Fees currency).',
      },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      academic_year: z.string().optional(),
      start_date: z.string().min(1),
      end_date: z.string().min(1),
      fee_amount: z.coerce.number().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
    { canDelete: false },
  ),
  'ops-school-trips': crud(
    formSection('Trip details', [
      { name: 'name', label: 'Trip name', type: 'text', required: true, colSpan: 2 },
      { name: 'destination', label: 'Destination', type: 'text', placeholder: 'Great Zimbabwe' },
      { name: 'trip_date', label: 'Trip date', type: 'date', required: true },
      { name: 'return_date', label: 'Return date', type: 'date' },
      {
        name: 'fee_amount',
        label: 'Fee per student',
        type: 'number',
        placeholder: '0.00',
        description: 'Charged in the school fees currency (Settings → Fees currency).',
      },
      {
        name: 'capacity',
        label: 'Capacity',
        type: 'number',
        placeholder: 'Leave blank for unlimited',
        description: 'Maximum number of students who can register.',
      },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
      {
        name: 'open_for_registration',
        label: 'Open for parent registration',
        type: 'checkbox',
        colSpan: 2,
      },
    ]),
    z.object({
      name: z.string().min(1),
      destination: z.string().optional(),
      trip_date: z.string().min(1),
      return_date: z.string().optional(),
      fee_amount: z.coerce.number().optional(),
      capacity: z.coerce.number().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
      open_for_registration: z.boolean().optional(),
    }),
    { canDelete: false },
  ),
  'finance-payments': crud(
    [
      {
        name: 'student_id',
        label: 'Student',
        type: 'relation',
        required: true,
        placeholder: 'Select student',
        colSpan: 2,
        relation: studentRelation(),
      },
      {
        name: 'invoice_id',
        label: 'Invoice',
        type: 'relation',
        required: true,
        placeholder: 'Select unpaid invoice',
        colSpan: 2,
        relation: invoiceRelation({
          dependsOn: { field: 'student_id', paramKey: 'student_id' },
        }),
      },
      { name: 'amount', label: 'Amount', type: 'number', required: true, placeholder: '0.00' },
      {
        name: 'method',
        label: 'Payment method',
        type: 'select',
        required: true,
        options: [...PAYMENT_METHOD_OPTIONS],
      },
      {
        name: 'income_head_id',
        label: 'Income head (optional)',
        type: 'relation',
        placeholder: 'Classify this receipt',
        description: 'Links the ledger credit to an income head for accounting reports.',
        relation: incomeHeadRelation(),
        colSpan: 2,
      },
      { name: 'reference', label: 'Reference / receipt no.', type: 'text', placeholder: 'Optional transaction reference' },
      { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Optional internal note' },
    ],
    z.object({
      student_id: z.string().min(1, 'Select a student'),
      invoice_id: z.string().min(1, 'Select an invoice'),
      amount: z.coerce.number().positive('Amount must be greater than zero'),
      method: z.string().min(1, 'Select a payment method'),
      income_head_id: z.string().optional().or(z.literal('')),
      reference: z.string().optional(),
      notes: z.string().optional(),
    }),
    { canEdit: false, canDelete: false },
  ),
  'finance-invoices': crud(
    [
      {
        name: 'student_id',
        label: 'Student',
        type: 'relation',
        required: true,
        placeholder: 'Select student',
        colSpan: 2,
        relation: studentRelation(),
      },
      {
        name: 'fee_group_id',
        label: 'Fee group (optional)',
        type: 'relation',
        placeholder: 'Bill a fee group for this student\'s class',
        description: 'When set, creates invoices from matching fee structures. Amount below is ignored.',
        relation: feeGroupRelation(),
        colSpan: 1,
      },
      {
        name: 'fee_structure_id',
        label: 'Fee structure (optional)',
        type: 'relation',
        placeholder: 'Link a fee structure',
        description: 'Used for discount matching by fee category.',
        relation: feeStructureRelation(),
        colSpan: 1,
      },
      {
        name: 'description',
        label: 'Description',
        type: 'text',
        required: true,
        placeholder: 'Term 1 tuition, exam fees…',
        colSpan: 2,
        description: 'Required for manual invoices. Optional when using a fee group.',
      },
      { name: 'amount', label: 'Amount', type: 'number', required: true, description: 'Ignored when a fee group is selected.' },
      { name: 'due_date', label: 'Due date', type: 'date', required: true },
      {
        name: 'apply_discounts',
        label: 'Apply matching fee discounts',
        type: 'checkbox',
        description: 'Uses active discounts for the student category and fee category.',
      },
      {
        name: 'combine_group',
        label: 'Combine fee group into one invoice',
        type: 'checkbox',
        description: 'Otherwise one invoice is created per fee structure in the group.',
      },
    ],
    z.object({
      student_id: z.string().min(1, 'Select a student'),
      fee_group_id: z.string().optional().or(z.literal('')),
      fee_structure_id: z.string().optional().or(z.literal('')),
      description: z.string().optional().or(z.literal('')),
      amount: z.coerce.number().optional(),
      due_date: z.string().min(1, 'Due date is required'),
      apply_discounts: z.boolean().optional(),
      combine_group: z.boolean().optional(),
    }).superRefine((data, ctx) => {
      if (!data.fee_group_id) {
        if (!data.description?.trim()) {
          ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Description is required', path: ['description'] })
        }
        if (data.amount == null || Number(data.amount) <= 0) {
          ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Amount must be greater than zero', path: ['amount'] })
        }
      }
    }),
    { canDelete: false },
  ),
  'finance-fees': crud(
    [
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        required: true,
        placeholder: 'Select class',
        description: 'Class this fee structure applies to.',
        relation: classRelation(),
      },
      {
        name: 'fee_category_id',
        label: 'Fee category',
        type: 'relation',
        required: true,
        placeholder: 'Select category',
        description: 'Choose from Fee Categories. Create a category first if needed.',
        relation: feeCategoryRelation(),
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        required: true,
        description: 'Uses the school fees currency from Settings.',
      },
    ],
    z.object({
      class_id: z.string().min(1, 'Select a class'),
      fee_category_id: z.string().min(1, 'Select a fee category'),
      amount: z.coerce.number().positive('Amount must be greater than zero'),
    }),
  ),
  'finance-fee-categories': crud(
    [
      { name: 'name', label: 'Category name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      {
        name: 'is_active',
        label: 'Active',
        type: 'checkbox',
        description: 'Inactive categories stay in history but are hidden from new fee structures.',
      },
      {
        name: 'order',
        label: 'Display order',
        type: 'number',
        placeholder: '0',
        description: 'Lower numbers appear first in pickers.',
      },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
      order: z.coerce.number().min(0).optional(),
    }),
  ),
  'finance-fee-groups': crud(
    [
      { name: 'name', label: 'Group name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      {
        name: 'fee_category_ids',
        label: 'Fee categories',
        type: 'multirelation',
        description: 'Select the fee categories included in this billing group.',
        relation: feeCategoryRelation({ moduleLabel: 'fee category' }),
        colSpan: 2,
      },
      {
        name: 'is_active',
        label: 'Active',
        type: 'checkbox',
        description: 'Inactive groups stay in history but are hidden from new invoices.',
      },
      {
        name: 'order',
        label: 'Display order',
        type: 'number',
        placeholder: '0',
      },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      description: z.string().optional(),
      fee_category_ids: z.string().optional().or(z.literal('')),
      is_active: z.boolean().optional(),
      order: z.coerce.number().min(0).optional(),
    }),
  ),
  'finance-fee-discounts': crud(
    formSection('Discount details', [
      { name: 'name', label: 'Discount name', type: 'text', required: true, colSpan: 2 },
      {
        name: 'discount_type',
        label: 'Discount type',
        type: 'select',
        required: true,
        options: [
          { label: 'Percent', value: 'percent' },
          { label: 'Fixed amount', value: 'fixed' },
        ],
      },
      { name: 'value', label: 'Value', type: 'number', required: true, placeholder: '0' },
      {
        name: 'fee_category_id',
        label: 'Fee category',
        type: 'relation',
        relation: feeCategoryRelation(),
      },
      {
        name: 'student_category_id',
        label: 'Student category',
        type: 'relation',
        relation: studentCategoryRelation(),
      },
      { name: 'starts_on', label: 'Starts on', type: 'date' },
      { name: 'ends_on', label: 'Ends on', type: 'date' },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        colSpan: 2,
        placeholder: 'Optional notes about when this discount applies',
      },
      {
        name: 'is_active',
        label: 'Active',
        type: 'checkbox',
        colSpan: 2,
      },
    ]),
    z.object({
      name: z.string().min(1, 'Name is required'),
      discount_type: z.enum(['percent', 'fixed']),
      value: z.coerce.number().min(0),
      fee_category_id: z.string().optional().or(z.literal('')),
      student_category_id: z.string().optional().or(z.literal('')),
      starts_on: z.string().optional().or(z.literal('')),
      ends_on: z.string().optional().or(z.literal('')),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'finance-income-heads': crud(
    [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', placeholder: 'INC-001' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      code: z.string().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'finance-expense-heads': crud(
    [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', placeholder: 'EXP-001' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      code: z.string().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'finance-transactions': crud([], z.object({}), { canCreate: false, canEdit: false, canDelete: false }),
  'finance-income': crud(
    [
      { name: 'description', label: 'Description', type: 'text', required: true, colSpan: 2, placeholder: 'e.g. Donation, hall hire…' },
      { name: 'amount', label: 'Amount', type: 'number', required: true, placeholder: '0.00' },
      {
        name: 'income_head_id',
        label: 'Income head',
        type: 'relation',
        required: true,
        placeholder: 'Classify this income',
        relation: incomeHeadRelation(),
      },
      { name: 'date', label: 'Date', type: 'date' },
      {
        name: 'payment_method',
        label: 'Payment method',
        type: 'select',
        placeholder: 'Optional',
        options: [...PAYMENT_METHOD_OPTIONS],
      },
      {
        name: 'currency',
        label: 'Currency',
        type: 'select',
        options: [
          { label: 'USD', value: 'USD' },
          { label: 'ZWG', value: 'ZWG' },
        ],
      },
      { name: 'reference', label: 'Reference', type: 'text', placeholder: 'Optional receipt/reference' },
      { name: 'notes', label: 'Notes', type: 'textarea', colSpan: 2, placeholder: 'Optional note' },
    ],
    z.object({
      description: z.string().min(1, 'Description is required'),
      amount: z.coerce.number().positive('Amount must be greater than zero'),
      income_head_id: z.string().min(1, 'Select an income head'),
      date: z.string().optional().or(z.literal('')),
      payment_method: z.string().optional().or(z.literal('')),
      currency: z.string().optional().or(z.literal('')),
      reference: z.string().optional(),
      notes: z.string().optional(),
    }),
  ),
  'finance-expense': crud(
    [
      { name: 'description', label: 'Description', type: 'text', required: true, colSpan: 2, placeholder: 'e.g. Utilities, repairs…' },
      { name: 'amount', label: 'Amount', type: 'number', required: true, placeholder: '0.00' },
      {
        name: 'expense_head_id',
        label: 'Expense head',
        type: 'relation',
        required: true,
        placeholder: 'Classify this expense',
        relation: expenseHeadRelation(),
      },
      { name: 'date', label: 'Date', type: 'date' },
      {
        name: 'payment_method',
        label: 'Payment method',
        type: 'select',
        placeholder: 'Optional',
        options: [...PAYMENT_METHOD_OPTIONS],
      },
      {
        name: 'currency',
        label: 'Currency',
        type: 'select',
        options: [
          { label: 'USD', value: 'USD' },
          { label: 'ZWG', value: 'ZWG' },
        ],
      },
      { name: 'reference', label: 'Reference', type: 'text', placeholder: 'Optional receipt/reference' },
      { name: 'notes', label: 'Notes', type: 'textarea', colSpan: 2, placeholder: 'Optional note' },
    ],
    z.object({
      description: z.string().min(1, 'Description is required'),
      amount: z.coerce.number().positive('Amount must be greater than zero'),
      expense_head_id: z.string().min(1, 'Select an expense head'),
      date: z.string().optional().or(z.literal('')),
      payment_method: z.string().optional().or(z.literal('')),
      currency: z.string().optional().or(z.literal('')),
      reference: z.string().optional(),
      notes: z.string().optional(),
    }),
  ),
  'finance-payroll': crud(
    formSection('Payroll adjustment', [
      {
        name: 'base_salary',
        label: 'Base salary',
        type: 'number',
        required: true,
        description: 'Gross and net recalculate from base plus existing allowances and deductions.',
      },
      {
        name: 'notes',
        label: 'Notes',
        type: 'textarea',
        placeholder: 'Optional adjustment note',
        colSpan: 2,
      },
    ]),
    z.object({
      base_salary: z.coerce.number().min(0, 'Base salary must be zero or more'),
      notes: z.string().optional(),
    }),
    { canCreate: false, canDelete: false },
  ),
  'ops-inventory': crud(
    [
      ...formSection('Item details', [
        { name: 'name', label: 'Item name', type: 'text', required: true, placeholder: 'School blazer' },
        { name: 'sku', label: 'SKU', type: 'text', placeholder: 'BLZ-M' },
        {
          name: 'type',
          label: 'Type',
          type: 'select',
          required: true,
          options: [
            { label: 'Uniform', value: 'uniform' },
            { label: 'Stationery', value: 'stationery' },
            { label: 'Book', value: 'book' },
            { label: 'Equipment', value: 'equipment' },
            { label: 'Other', value: 'other' },
          ],
        },
        { name: 'size', label: 'Size / variant', type: 'text', placeholder: 'M, A4, …' },
        {
          name: 'description',
          label: 'Description',
          type: 'textarea',
          colSpan: 2,
          placeholder: 'Optional notes for this item',
        },
      ]),
      ...formSection('Stock & pricing', [
        { name: 'stock_quantity', label: 'Stock on hand', type: 'number', required: true, placeholder: '0' },
        { name: 'reorder_level', label: 'Reorder level', type: 'number', placeholder: '5' },
        { name: 'unit_price', label: 'Unit price', type: 'number', required: true, placeholder: '0.00' },
        {
          name: 'billing_mode',
          label: 'Billing mode',
          type: 'select',
          required: true,
          options: [
            { label: 'Direct sale', value: 'direct_sale' },
            { label: 'Mandatory fee', value: 'mandatory_fee' },
            { label: 'Both', value: 'both' },
          ],
        },
      ]),
      {
        name: 'is_active',
        label: 'Active',
        type: 'checkbox',
        section: 'Status',
        description: 'Inactive items stay in history but are hidden from new sales.',
      },
    ],
    z.object({
      name: z.string().min(1, 'Item name is required'),
      sku: z.string().optional(),
      type: z.enum(['uniform', 'stationery', 'book', 'equipment', 'other']),
      size: z.string().optional(),
      description: z.string().optional(),
      stock_quantity: z.coerce.number().min(0),
      reorder_level: z.coerce.number().min(0).optional(),
      unit_price: z.coerce.number().min(0),
      billing_mode: z.enum(['direct_sale', 'mandatory_fee', 'both']),
      is_active: z.boolean().optional(),
    }),
    { canDelete: false, staged: false },
  ),
  'ops-inventory-sales': crud(
    formSection('Sale details', [
      {
        name: 'item_id',
        label: 'Inventory item',
        type: 'relation',
        required: true,
        placeholder: 'Select item',
        relation: inventoryItemRelation(),
      },
      { name: 'quantity', label: 'Quantity', type: 'number', required: true, placeholder: '1' },
      {
        name: 'payment_method',
        label: 'Payment method',
        type: 'select',
        required: true,
        options: [
          { label: 'Cash', value: 'cash' },
          { label: 'Student account', value: 'student_account' },
          { label: 'Upfront', value: 'upfront' },
        ],
      },
      {
        name: 'student_id',
        label: 'Student',
        type: 'relation',
        placeholder: 'Optional — link to student',
        colSpan: 2,
        relation: studentRelation(),
      },
      { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Optional note for this sale', colSpan: 2 },
    ]),
    z.object({
      item_id: z.string().min(1, 'Select an inventory item'),
      quantity: z.coerce.number().min(1),
      payment_method: z.enum(['cash', 'student_account', 'upfront']),
      student_id: z.string().optional().or(z.literal('')),
      notes: z.string().optional(),
    }),
    { canEdit: false, canDelete: false },
  ),
  'ops-procurement': crud(
    formSection('Spend request', [
      { name: 'title', label: 'What is the money for?', type: 'text', required: true, colSpan: 2 },
      {
        name: 'spend_type',
        label: 'Spend type',
        type: 'select',
        required: true,
        options: [
          { label: 'Procurement / purchase', value: 'procurement' },
          { label: 'Petty cash', value: 'petty_cash' },
          { label: 'Utilities', value: 'utilities' },
          { label: 'Travel', value: 'travel' },
          { label: 'Maintenance', value: 'maintenance' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        name: 'department_id',
        label: 'Department',
        type: 'relation',
        placeholder: 'Select department',
        relation: departmentRelation(),
      },
      { name: 'description', label: 'Justification', type: 'textarea', colSpan: 2 },
      { name: 'item_description', label: 'Line item', type: 'text', required: true, colSpan: 2 },
      { name: 'item_quantity', label: 'Quantity', type: 'number', required: true, placeholder: '1' },
      { name: 'item_unit_cost', label: 'Unit cost', type: 'number', required: true, placeholder: '0.00' },
      {
        name: 'submit',
        label: 'Submit for approval now',
        type: 'checkbox',
        description: 'Starts the approval workflow. Leave unchecked to save as draft.',
        colSpan: 2,
      },
    ]),
    z.object({
      title: z.string().min(1),
      spend_type: z.enum(['procurement', 'petty_cash', 'utilities', 'travel', 'maintenance', 'other']),
      department_id: z.string().optional().or(z.literal('')),
      description: z.string().optional(),
      item_description: z.string().min(1, 'Item description is required'),
      item_quantity: z.coerce.number().min(1),
      item_unit_cost: z.coerce.number().min(0),
      submit: z.boolean().optional(),
    }),
    { canEdit: false, canDelete: false },
  ),
  'ops-procurement-vendors': crud(
    formSection('Vendor', [
      { name: 'name', label: 'Vendor name', type: 'text', required: true, colSpan: 2 },
      { name: 'contact_person', label: 'Contact person', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'phone' },
      { name: 'address', label: 'Address', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      name: z.string().min(1),
      contact_person: z.string().optional(),
      email: z.string().email().optional().or(z.literal('')),
      phone: z.string().optional(),
      address: z.string().optional(),
    }),
    { canEdit: true, canDelete: false },
  ),
  'ops-library': crud(
    formSection('Book details', [
      { name: 'title', label: 'Title', type: 'text', required: true, colSpan: 2 },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'isbn', label: 'ISBN', type: 'text' },
      { name: 'total_copies', label: 'Total copies', type: 'number', placeholder: '1' },
      { name: 'category', label: 'Category', type: 'text', placeholder: 'Fiction, Textbook…' },
    ]),
    z.object({
      title: z.string().min(1),
      author: z.string().optional(),
      isbn: z.string().optional(),
      total_copies: z.coerce.number().min(1).optional(),
      category: z.string().optional(),
    }),
    { canEdit: true, canDelete: true },
  ),
  'ops-transport': crud(
    formSection('Vehicle details', [
      {
        name: 'registration_number',
        label: 'Registration number',
        type: 'text',
        required: true,
        placeholder: 'AEB 1234',
      },
      { name: 'make', label: 'Make', type: 'text', placeholder: 'Toyota' },
      { name: 'model', label: 'Model', type: 'text', placeholder: 'Hiace' },
      { name: 'capacity', label: 'Seat capacity', type: 'number', placeholder: '16' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
          { label: 'Maintenance', value: 'maintenance' },
        ],
      },
    ]),
    z.object({
      registration_number: z.string().min(1, 'Registration is required'),
      make: z.string().optional(),
      model: z.string().optional(),
      capacity: z.coerce.number().int().min(1).optional(),
      status: z.enum(['active', 'inactive', 'maintenance']),
    }),
    { canEdit: true, canDelete: false, staged: false },
  ),
  'ops-transport-drivers': crud(
    formSection('Driver details', [
      { name: 'name', label: 'Full name', type: 'text', required: true },
      { name: 'license_number', label: 'License number', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'phone' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
    ]),
    z.object({
      name: z.string().min(1, 'Name is required'),
      license_number: z.string().optional(),
      phone: z.string().optional(),
      status: z.enum(['active', 'inactive']),
    }),
    { canEdit: true, canDelete: false, staged: false },
  ),
  'ops-transport-routes': crud(
    formSection('Route details', [
      { name: 'name', label: 'Route name', type: 'text', required: true, placeholder: 'Mufakose Central' },
      {
        name: 'vehicle_id',
        label: 'Vehicle',
        type: 'relation',
        placeholder: 'Select vehicle',
        relation: transportVehicleRelation(),
      },
      {
        name: 'driver_id',
        label: 'Driver',
        type: 'relation',
        placeholder: 'Select driver',
        relation: transportDriverRelation(),
      },
      {
        name: 'route_description',
        label: 'Description',
        type: 'textarea',
        colSpan: 2,
        placeholder: 'Pickup points and notes',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
    ]),
    z.object({
      name: z.string().min(1, 'Route name is required'),
      vehicle_id: z.string().optional().or(z.literal('')),
      driver_id: z.string().optional().or(z.literal('')),
      route_description: z.string().optional(),
      status: z.enum(['active', 'inactive']),
    }),
    { canEdit: true, canDelete: false, staged: false },
  ),
  'ops-assets': crud(
    formSection('Asset details', [
      { name: 'asset_tag', label: 'Asset tag', type: 'text', placeholder: 'AST-0001' },
      { name: 'name', label: 'Asset name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true, placeholder: 'Furniture, IT, Lab…' },
      { name: 'purchase_date', label: 'Purchase date', type: 'date' },
      { name: 'purchase_cost', label: 'Purchase cost', type: 'number', placeholder: '0.00' },
      { name: 'location', label: 'Location', type: 'text' },
      {
        name: 'custodian_user_id',
        label: 'Custodian',
        type: 'relation',
        placeholder: 'Optional — assign a staff custodian',
        relation: staffUserRelation(),
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Maintenance', value: 'maintenance' },
          { label: 'Disposed', value: 'disposed' },
        ],
      },
    ]),
    z.object({
      asset_tag: z.string().optional(),
      name: z.string().min(1),
      category: z.string().min(1, 'Category is required'),
      purchase_date: z.string().optional().or(z.literal('')),
      purchase_cost: z.coerce.number().min(0).optional(),
      location: z.string().optional(),
      custodian_user_id: z.string().optional().or(z.literal('')),
      status: z.enum(['active', 'maintenance', 'disposed']).optional(),
    }),
    { canEdit: true, canDelete: false },
  ),
  'ops-hostels': crud(
    formSection('Hostel details', [
      { name: 'name', label: 'Hostel name', type: 'text', required: true },
      {
        name: 'gender',
        label: 'Gender',
        type: 'select',
        required: true,
        options: [{ label: 'Male', value: 'male' }, { label: 'Female', value: 'female' }, { label: 'Mixed', value: 'mixed' }],
      },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
    ]),
    z.object({
      name: z.string().min(1),
      gender: z.enum(['male', 'female', 'mixed']),
      capacity: z.coerce.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    }),
    { canEdit: true, canDelete: false },
  ),
  'ops-visitors': crud(
    formSection('Visitor check-in', [
      { name: 'name', label: 'Full name', type: 'text', required: true, placeholder: 'Visitor name' },
      { name: 'phone', label: 'Phone', type: 'phone' },
      { name: 'id_number', label: 'ID / passport number', type: 'text', placeholder: 'Optional' },
      { name: 'purpose', label: 'Purpose of visit', type: 'text', required: true, placeholder: 'Meeting, pickup, delivery…', colSpan: 2 },
      {
        name: 'host_user_id',
        label: 'Host staff',
        type: 'relation',
        placeholder: 'Optional — who they are visiting',
        relation: staffUserRelation(),
      },
      {
        name: 'student_id',
        label: 'Related student',
        type: 'relation',
        placeholder: 'Optional — if visiting a student',
        relation: studentRelation(),
      },
    ]),
    z.object({
      name: z.string().min(1, 'Name is required'),
      phone: z.string().optional(),
      id_number: z.string().optional(),
      purpose: z.string().min(1, 'Purpose is required'),
      host_user_id: z.string().optional().or(z.literal('')),
      student_id: z.string().optional().or(z.literal('')),
    }),
    { canEdit: false, canDelete: false, staged: false },
  ),
  'ops-health': crud(
    formSection('Clinic visit', [
      {
        name: 'student_id',
        label: 'Student',
        type: 'relation',
        required: true,
        placeholder: 'Select student',
        colSpan: 2,
        relation: studentRelation(),
      },
      { name: 'visit_date', label: 'Visit date', type: 'date', required: true },
      { name: 'complaint', label: 'Complaint / reason', type: 'textarea', required: true, colSpan: 2 },
      { name: 'diagnosis', label: 'Diagnosis / notes', type: 'textarea', colSpan: 2 },
      { name: 'treatment', label: 'Treatment', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      student_id: z.string().min(1, 'Select a student'),
      visit_date: z.string().min(1),
      complaint: z.string().min(1, 'Complaint is required'),
      diagnosis: z.string().optional(),
      treatment: z.string().optional(),
    }),
    { canEdit: true, canDelete: false },
  ),
  'ops-events': crud(
    formSection('Event details', [
      { name: 'title', label: 'Event title', type: 'text', required: true, colSpan: 2 },
      { name: 'type', label: 'Type', type: 'text', placeholder: 'Sports day, Meeting, Holiday…' },
      { name: 'starts_at', label: 'Starts at', type: 'date', required: true },
      { name: 'ends_at', label: 'Ends at', type: 'date' },
      { name: 'location', label: 'Location', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Scheduled', value: 'scheduled' },
          { label: 'Ongoing', value: 'ongoing' },
          { label: 'Completed', value: 'completed' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      title: z.string().min(1),
      type: z.string().optional(),
      starts_at: z.string().min(1),
      ends_at: z.string().optional().or(z.literal('')),
      location: z.string().optional(),
      status: z.enum(['scheduled', 'ongoing', 'completed', 'cancelled']).optional(),
      description: z.string().optional(),
    }),
    { canEdit: true, canDelete: true },
  ),
  'comms-announcements': crud(
    [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'message', label: 'Message', type: 'textarea' },
      {
        name: 'type',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'Information', value: 'info' },
          { label: 'Important', value: 'important' },
          { label: 'Warning', value: 'warning' },
          { label: 'Success', value: 'success' },
        ],
      },
      {
        name: 'target_audience',
        label: 'Audience',
        type: 'select',
        options: [
          { label: 'Everyone', value: 'all' },
          { label: 'Parents', value: 'parents' },
        ],
      },
      { name: 'date', label: 'Publish date', type: 'date' },
      { name: 'is_active', label: 'Visible', type: 'checkbox' },
    ],
    z.object({
      title: z.string().min(1),
      message: z.string().min(1),
      type: z.string().min(1),
      target_audience: z.enum(['all', 'parents']),
      date: z.string().min(1),
    }),
  ),
  'hr-leave': crud(
    leaveFormFields,
    leaveFormSchema,
    { canEdit: false, canDelete: false },
  ),
  'hr-leave-types': crud(
    [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', placeholder: 'ANNUAL' },
      { name: 'default_days', label: 'Default days', type: 'number', placeholder: '20' },
      { name: 'is_paid', label: 'Paid leave', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2 },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      code: z.string().optional(),
      default_days: z.coerce.number().min(0).optional(),
      is_paid: z.boolean().optional(),
      is_active: z.boolean().optional(),
      description: z.string().optional(),
    }),
  ),
  'hr-designations': crud(
    [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', placeholder: 'HOD' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      code: z.string().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'hr-employees': crud(
    formSection('Employee details', [
      { name: 'first_name', label: 'First name', type: 'text', required: true },
      { name: 'last_name', label: 'Last name', type: 'text', required: true },
      { name: 'employee_number', label: 'Employee number', type: 'text', placeholder: 'EMP-001' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'phone' },
      {
        name: 'designation_id',
        label: 'Designation',
        type: 'relation',
        relation: designationRelation(),
      },
      {
        name: 'department_id',
        label: 'Department',
        type: 'relation',
        relation: departmentRelation(),
      },
      {
        name: 'employment_type',
        label: 'Employment type',
        type: 'select',
        options: [
          { label: 'Full time', value: 'full_time' },
          { label: 'Part time', value: 'part_time' },
          { label: 'Contract', value: 'contract' },
          { label: 'Temporary', value: 'temporary' },
        ],
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
          { label: 'On leave', value: 'on_leave' },
          { label: 'Terminated', value: 'terminated' },
        ],
      },
      { name: 'joining_date', label: 'Joining date', type: 'date' },
      { name: 'base_salary', label: 'Base salary', type: 'number', placeholder: '0.00' },
    ]),
    z.object({
      first_name: z.string().min(1, 'First name is required'),
      last_name: z.string().min(1, 'Last name is required'),
      employee_number: z.string().optional(),
      email: z.string().email().optional().or(z.literal('')),
      phone: z.string().optional(),
      designation_id: z.string().optional().or(z.literal('')),
      department_id: z.string().optional().or(z.literal('')),
      employment_type: z.string().optional(),
      status: z.string().optional(),
      joining_date: z.string().optional().or(z.literal('')),
      base_salary: z.coerce.number().min(0).optional(),
    }),
  ),
  'people-student-categories': crud(
    [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', placeholder: 'BOARDER' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
      { name: 'order', label: 'Display order', type: 'number', placeholder: '0' },
    ],
    z.object({
      name: z.string().min(1, 'Name is required'),
      code: z.string().optional(),
      description: z.string().optional(),
      is_active: z.boolean().optional(),
      order: z.coerce.number().min(0).optional(),
    }),
  ),
  'academics-certificate-templates': crud(
    formSection('Template', [
      { name: 'name', label: 'Template name', type: 'text', required: true },
      { name: 'certificate_type', label: 'Certificate type', type: 'text', required: true, placeholder: 'completion' },
      { name: 'title', label: 'Title', type: 'text', required: true, colSpan: 2 },
      {
        name: 'body_html',
        label: 'Body HTML',
        type: 'textarea',
        required: true,
        colSpan: 2,
        description: 'Use placeholders {{student_name}}, {{date}}, and {{school_name}}.',
        placeholder: '<p>This certifies that {{student_name}}…</p>',
      },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ]),
    z.object({
      name: z.string().min(1, 'Name is required'),
      certificate_type: z.string().min(1, 'Type is required'),
      title: z.string().min(1, 'Title is required'),
      body_html: z.string().min(1, 'Body is required'),
      is_active: z.boolean().optional(),
    }),
  ),
  'academics-school-certificates': crud([], z.object({}), {
    canCreate: false,
    canEdit: false,
    canDelete: false,
  }),
  'academics-exam-schedules': crud(
    formSection('Schedule', [
      {
        name: 'exam_id',
        label: 'Exam',
        type: 'relation',
        required: true,
        relation: { endpoint: moduleEndpoints.exams, moduleLabel: 'exam' },
      },
      {
        name: 'class_id',
        label: 'Class',
        type: 'relation',
        required: true,
        relation: classRelation(),
      },
      {
        name: 'subject_id',
        label: 'Subject',
        type: 'relation',
        required: true,
        relation: subjectRelation(),
      },
      {
        name: 'room_id',
        label: 'Room',
        type: 'relation',
        relation: { endpoint: moduleEndpoints.rooms, moduleLabel: 'room' },
      },
      {
        name: 'starts_at',
        label: 'Starts at',
        type: 'datetime-local',
        required: true,
        description: 'Exam start date and time.',
      },
      {
        name: 'ends_at',
        label: 'Ends at',
        type: 'datetime-local',
      },
      { name: 'duration_minutes', label: 'Duration (minutes)', type: 'number' },
      { name: 'invigilator', label: 'Invigilator', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      exam_id: z.string().min(1, 'Select an exam'),
      class_id: z.string().min(1, 'Select a class'),
      subject_id: z.string().min(1, 'Select a subject'),
      room_id: z.string().optional().or(z.literal('')),
      starts_at: z.string().min(1, 'Start time is required'),
      ends_at: z.string().optional().or(z.literal('')),
      duration_minutes: z.coerce.number().min(1).optional(),
      invigilator: z.string().optional(),
      notes: z.string().optional(),
    }),
  ),
  'ops-library-members': crud(
    formSection('Member', [
      {
        name: 'member_type',
        label: 'Member type',
        type: 'select',
        required: true,
        options: [
          { label: 'Student', value: 'student' },
          { label: 'Teacher', value: 'teacher' },
          { label: 'Employee', value: 'employee' },
          { label: 'External', value: 'external' },
        ],
      },
      {
        name: 'member_id',
        label: 'Student',
        type: 'relation',
        colSpan: 2,
        placeholder: 'Select a student',
        description: 'Optional link — selecting fills the member name when empty.',
        visibleWhen: { field: 'member_type', equals: 'student' },
        relation: {
          endpoint: moduleEndpoints.students,
          moduleLabel: 'student',
          params: { all: true },
          fillEmptyField: 'name',
        },
      },
      {
        name: 'member_id',
        label: 'Teacher',
        type: 'relation',
        colSpan: 2,
        placeholder: 'Select a teacher',
        description: 'Optional link — selecting fills the member name when empty.',
        visibleWhen: { field: 'member_type', equals: 'teacher' },
        relation: {
          endpoint: moduleEndpoints.teachers,
          moduleLabel: 'teacher',
          params: { all: true },
          fillEmptyField: 'name',
        },
      },
      {
        name: 'member_id',
        label: 'Employee',
        type: 'relation',
        colSpan: 2,
        placeholder: 'Select an employee',
        description: 'Optional link — selecting fills the member name when empty.',
        visibleWhen: { field: 'member_type', equals: 'employee' },
        relation: {
          endpoint: moduleEndpoints.employees,
          moduleLabel: 'employee',
          params: { all: true },
          fillEmptyField: 'name',
        },
      },
      { name: 'member_number', label: 'Member number', type: 'text', placeholder: 'LIB-001' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'phone' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Suspended', value: 'suspended' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
      { name: 'joined_on', label: 'Joined on', type: 'date' },
      { name: 'notes', label: 'Notes', type: 'textarea', colSpan: 2 },
    ]),
    z.object({
      member_type: z.enum(['student', 'teacher', 'employee', 'external']),
      member_id: z.preprocess(
        (value) => (value === '' || value == null ? undefined : value),
        z.coerce.number().optional(),
      ),
      member_number: z.string().optional(),
      name: z.string().min(1, 'Name is required'),
      email: z.string().email().optional().or(z.literal('')),
      phone: z.string().optional(),
      status: z.string().optional(),
      joined_on: z.string().optional().or(z.literal('')),
      notes: z.string().optional(),
    }),
  ),
  'ops-library-loans': crud(
    formSection('Loan', [
      {
        name: 'book_id',
        label: 'Book',
        type: 'relation',
        required: true,
        colSpan: 2,
        placeholder: 'Select a book',
        relation: {
          endpoint: moduleEndpoints.libraryBooks,
          moduleLabel: 'book',
          params: { all: true },
        },
      },
      {
        name: 'library_member_id',
        label: 'Library member',
        type: 'relation',
        required: true,
        colSpan: 2,
        placeholder: 'Select a member',
        relation: {
          endpoint: moduleEndpoints.libraryMembers,
          moduleLabel: 'library member',
          params: { all: true, status: 'active' },
        },
      },
      { name: 'due_at', label: 'Due date', type: 'date', required: true, description: 'Today or a future date' },
    ]),
    z.object({
      book_id: z.string().min(1, 'Select a book'),
      library_member_id: z.string().min(1, 'Select a library member'),
      due_at: z.string().min(1, 'Due date is required'),
    }),
    { canCreate: true, canEdit: false, canDelete: false },
  ),
  'settings-currencies': crud(
    [
      { name: 'code', label: 'Code', type: 'text', required: true, placeholder: 'USD' },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'US Dollar' },
      { name: 'symbol', label: 'Symbol', type: 'text', placeholder: '$' },
      {
        name: 'is_default',
        label: 'Default currency',
        type: 'checkbox',
        description: 'Billing currency must be USD or ZWG.',
      },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    z.object({
      code: z
        .string()
        .min(1, 'Code is required')
        .max(3)
        .transform((v) => v.trim().toUpperCase())
        .refine((v) => v === 'USD' || v === 'ZWG', 'Code must be USD or ZWG'),
      name: z.string().min(1, 'Name is required'),
      symbol: z.string().optional(),
      is_default: z.boolean().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'settings-languages': crud(
    [
      { name: 'code', label: 'Code', type: 'text', required: true, placeholder: 'en' },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'English' },
      { name: 'is_default', label: 'Default language', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    z.object({
      code: z.string().min(1, 'Code is required').max(10),
      name: z.string().min(1, 'Name is required'),
      is_default: z.boolean().optional(),
      is_active: z.boolean().optional(),
    }),
  ),
  'hr-discipline': crud(
    formSection('Incident record', [
      {
        name: 'student_id',
        label: 'Student',
        type: 'relation',
        required: true,
        placeholder: 'Select student',
        colSpan: 2,
        relation: studentRelation(),
      },
      { name: 'incident_date', label: 'Incident date', type: 'date', required: true },
      {
        name: 'category',
        label: 'Category',
        type: 'text',
        required: true,
        placeholder: 'Misconduct, bullying, lateness…',
      },
      {
        name: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Minor', value: 'minor' },
          { label: 'Moderate', value: 'moderate' },
          { label: 'Major', value: 'major' },
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea', required: true, colSpan: 2 },
      { name: 'action_taken', label: 'Action taken', type: 'textarea', colSpan: 2 },
      {
        name: 'notify_parents',
        label: 'Notify parents',
        type: 'checkbox',
        description: 'Send a notification to the parents/guardians about this record.',
        colSpan: 2,
      },
    ]),
    z.object({
      student_id: z.string().min(1, 'Select a student'),
      incident_date: z.string().min(1),
      category: z.string().min(1, 'Category is required'),
      severity: z.enum(['minor', 'moderate', 'major']),
      description: z.string().min(1, 'Description is required'),
      action_taken: z.string().optional(),
      notify_parents: z.boolean().optional(),
    }),
    { canEdit: true, canDelete: false },
  ),
  compliance: crud(
    formSection('Policy', [
      { name: 'title', label: 'Policy title', type: 'text', required: true, colSpan: 2 },
      { name: 'category', label: 'Category', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Draft', value: 'draft' },
          { label: 'Archived', value: 'archived' },
        ],
      },
      { name: 'effective_date', label: 'Effective date', type: 'date' },
      { name: 'review_date', label: 'Review date', type: 'date' },
      { name: 'content', label: 'Content', type: 'textarea', required: true, colSpan: 2 },
    ]),
    z.object({
      title: z.string().min(1),
      category: z.string().optional(),
      status: z.enum(['active', 'draft', 'archived']).optional(),
      effective_date: z.string().optional().or(z.literal('')),
      review_date: z.string().optional().or(z.literal('')),
      content: z.string().min(1),
    }),
    { canEdit: true, canDelete: false },
  ),
  'compliance-incidents': crud(
    formSection('Incident report', [
      { name: 'category', label: 'Category', type: 'text', required: true },
      {
        name: 'severity',
        label: 'Severity',
        type: 'select',
        options: [
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
          { label: 'Critical', value: 'critical' },
        ],
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Open', value: 'open' },
          { label: 'Investigating', value: 'investigating' },
          { label: 'Resolved', value: 'resolved' },
          { label: 'Closed', value: 'closed' },
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea', required: true, colSpan: 2 },
    ]),
    z.object({
      category: z.string().min(1),
      severity: z.enum(['low', 'medium', 'high', 'critical']).optional().or(z.literal('')),
      status: z.enum(['open', 'investigating', 'resolved', 'closed']).optional(),
      description: z.string().min(1),
    }),
    { canEdit: true, canDelete: false },
  ),
  'compliance-consent': crud(
    formSection('Consent form', [
      { name: 'title', label: 'Form title', type: 'text', required: true, colSpan: 2 },
      {
        name: 'target_audience',
        label: 'Audience',
        type: 'select',
        options: [
          { label: 'Parents', value: 'parents' },
          { label: 'Students', value: 'students' },
          { label: 'Staff', value: 'staff' },
          { label: 'All', value: 'all' },
        ],
      },
      { name: 'due_date', label: 'Due date', type: 'date' },
      { name: 'requires_signature', label: 'Requires signature', type: 'checkbox' },
      { name: 'content', label: 'Form content', type: 'textarea', required: true, colSpan: 2 },
    ]),
    z.object({
      title: z.string().min(1),
      target_audience: z.string().optional(),
      due_date: z.string().optional().or(z.literal('')),
      requires_signature: z.boolean().optional(),
      content: z.string().min(1, 'Form content is required'),
    }),
    { canEdit: true, canDelete: false },
  ),
  'settings-custom-fields': crud(
    formSection('Custom field', [
      {
        name: 'entity_type',
        label: 'Entity type',
        type: 'select',
        required: true,
        options: [
          { label: 'Student', value: 'student' },
          { label: 'Teacher', value: 'teacher' },
          { label: 'Staff', value: 'staff' },
        ],
      },
      { name: 'name', label: 'Field name', type: 'text', required: true },
      {
        name: 'field_type',
        label: 'Field type',
        type: 'select',
        required: true,
        options: [
          { label: 'Text', value: 'text' },
          { label: 'Text area', value: 'textarea' },
          { label: 'Number', value: 'number' },
          { label: 'Date', value: 'date' },
          { label: 'Boolean', value: 'boolean' },
          { label: 'Select', value: 'select' },
          { label: 'Multi-select', value: 'multiselect' },
          { label: 'Email', value: 'email' },
          { label: 'Phone', value: 'phone' },
        ],
      },
      { name: 'is_required', label: 'Required', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ]),
    z.object({
      entity_type: z.string().min(1),
      name: z.string().min(1),
      field_type: z.string().min(1),
      is_required: z.boolean().optional(),
      is_active: z.boolean().optional(),
    }),
    { canEdit: true, canDelete: true },
  ),
}
