/** Canonical API v1 paths — keep in sync with routes/api/v1.php */
export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    schools: '/auth/schools',
    switchSchool: '/auth/switch-school',
    platformTerms: '/auth/platform-terms',
    privacyPolicy: '/auth/privacy-policy',
    acceptPlatformTerms: '/auth/accept-platform-terms',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/user/change-password',
  },
  profile: {
    show: '/user/profile',
    update: '/user/profile',
  },
  uploads: '/uploads',
  teacherPortal: {
    dashboard: '/teacher-portal/dashboard',
    classes: '/teacher-portal/classes',
    student: (id: number | string) => `/teacher-portal/students/${id}`,
    attendanceSubmit: '/teacher-portal/attendance/submit',
    attendanceLock: '/teacher-portal/attendance/lock',
    attendanceReports: '/teacher-portal/attendance/reports',
    freePeriods: '/teacher-portal/timetable/free-periods',
    examTimetable: '/teacher-portal/timetable/exams',
    timetableChangeRequests: '/teacher-portal/timetable/change-requests',
    calendar: '/teacher-portal/calendar',
    lessonPlans: '/teacher-portal/lesson-plans',
    lessonPlan: (id: number | string) => `/teacher-portal/lesson-plans/${id}`,
    syllabusTopics: '/teacher-portal/syllabus-topics',
    syllabusTopic: (id: number | string) => `/teacher-portal/syllabus-topics/${id}`,
    resources: '/teacher-portal/resources',
    submissions: (assignmentId: number | string) => `/teacher-portal/assignments/${assignmentId}/submissions`,
    storeSubmission: '/teacher-portal/submissions',
    gradeSubmission: (id: number | string) => `/teacher-portal/submissions/${id}/grade`,
    onlineLessons: '/teacher-portal/online-lessons',
    reportCards: '/teacher-portal/report-cards',
    behaviour: '/teacher-portal/behaviour',
    interventions: '/teacher-portal/interventions',
    participation: '/teacher-portal/participation',
    department: '/teacher-portal/department',
    leave: '/teacher-portal/leave',
    substitutions: '/teacher-portal/substitutions',
    acceptSubstitution: (id: number | string) => `/teacher-portal/substitutions/${id}/accept`,
    notifications: '/teacher-portal/notifications',
    markNotificationRead: (id: number | string) => `/teacher-portal/notifications/${id}/read`,
    markAllNotificationsRead: '/teacher-portal/notifications/read-all',
    aiGenerate: '/teacher-portal/ai/generate',
    export: '/teacher-portal/export',
  },
  studentPortal: {
    dashboard: '/student-portal/dashboard',
    me: '/student-portal/me',
    attendance: '/student-portal/attendance',
    grades: '/student-portal/grades',
    fees: '/student-portal/fees',
    timetable: '/student-portal/timetable',
    assignments: '/student-portal/assignments',
    announcements: '/student-portal/announcements',
  },
  school: {
    show: '/school',
    update: '/school',
    register: '/schools/register',
  },
  settings: {
    school: '/settings/school',
    config: '/settings/config',
    terminology: '/settings/terminology',
    customFields: '/settings/custom-fields',
    customField: (id: number | string) => `/settings/custom-fields/${id}`,
  },
  license: {
    status: '/license/status',
    activate: '/license/activate',
    admin: {
      list: '/admin/licenses',
      schools: '/admin/schools',
      createSchool: '/admin/schools',
      school: (id: number | string) => `/admin/schools/${id}`,
      schoolStatus: (id: number | string) => `/admin/schools/${id}/status`,
      schoolUsage: (id: number | string) => `/admin/schools/${id}/usage`,
      schoolBackups: (id: number | string) => `/admin/schools/${id}/backups`,
      restoreBackup: (schoolId: number | string, backupId: number | string) =>
        `/admin/schools/${schoolId}/backups/${backupId}/restore`,
      schoolDomains: (id: number | string) => `/admin/schools/${id}/domains`,
      schoolDomain: (schoolId: number | string, domainId: number | string) =>
        `/admin/schools/${schoolId}/domains/${domainId}`,
      verifyDomain: (schoolId: number | string, domainId: number | string) =>
        `/admin/schools/${schoolId}/domains/${domainId}/verify`,
      revoke: (id: number | string) => `/admin/licenses/${id}/revoke`,
    },
  },
  assistant: {
    status: '/assistant/status',
    chat: '/assistant/chat',
    conversations: '/assistant/conversations',
    conversation: (id: number | string) => `/assistant/conversations/${id}`,
  },
  dashboard: {
    kpis: '/dashboard/kpis',
    schoolWidgets: '/dashboard/school-widgets',
    lmsWidgets: '/dashboard/lms-widgets',
    rolePreview: (role: string) => `/dashboard/role-preview/${role}`,
    activity: '/dashboard/activity',
    monthlyStats: '/dashboard/monthly-stats',
    recentActivity: '/dashboard/recent-activity',
  },
  users: {
    list: '/users',
    detail: (id: number | string) => `/users/${id}`,
    activate: (id: number | string) => `/users/${id}/activate`,
    deactivate: (id: number | string) => `/users/${id}/deactivate`,
    resetPassword: (id: number | string) => `/users/${id}/reset-password`,
    assignRole: (id: number | string) => `/users/${id}/role`,
  },
  roles: {
    list: '/roles',
    detail: (id: number | string) => `/roles/${id}`,
  },
  permissions: { list: '/permissions' },
  students: {
    list: '/students',
    detail: (id: number | string) => `/students/${id}`,
    promote: '/students/promote',
    bulkInvoices: '/students/bulk/invoices',
    bulkStatus: '/students/bulk/status',
    bulkPromote: '/students/bulk/promote',
    performance: (id: number | string) => `/students/${id}/performance`,
    lifecycle: (id: number | string) => `/students/${id}/lifecycle`,
    placements: (id: number | string) => `/students/${id}/placements`,
    lifecycleTransition: (id: number | string) => `/students/${id}/lifecycle/transition`,
    lifecyclePromote: (id: number | string) => `/students/${id}/lifecycle/promote`,
    transferCertificate: (id: number | string) => `/students/${id}/transfer-certificate`,
    transcript: (id: number | string) => `/students/${id}/transcript`,
    invoices: (id: number | string) => `/students/${id}/invoices`,
    createInvoice: (id: number | string) => `/students/${id}/invoices`,
    documents: (id: number | string) => `/students/${id}/documents`,
    exams: (id: number | string) => `/students/${id}/exams`,
    resultsDownload: (id: number | string) => `/students/${id}/results/download`,
    idCardPrint: (id: number | string) => `/students/${id}/id-card/print`,
    photo: (id: number | string) => `/students/${id}/photo`,
    guardians: (id: number | string) => `/students/${id}/guardians`,
  },
  streams: {
    list: '/streams',
    detail: (id: number | string) => `/streams/${id}`,
  },
  houses: {
    list: '/houses',
    detail: (id: number | string) => `/houses/${id}`,
  },
  subjectPackages: {
    list: '/subject-packages',
    store: '/subject-packages',
    detail: (id: number | string) => `/subject-packages/${id}`,
  },
  teachers: {
    list: '/teachers',
    detail: (id: number | string) => `/teachers/${id}`,
    status: (id: number | string) => `/teachers/${id}/status`,
  },
  guardians: {
    list: '/guardians',
    detail: (id: number | string) => `/guardians/${id}`,
    students: (id: number | string) => `/guardians/${id}/students`,
    linkStudent: (id: number | string) => `/guardians/${id}/link-student`,
  },
  enrollment: {
    list: '/enrollment-applications',
    detail: (id: number | string) => `/enrollment-applications/${id}`,
    approve: (id: number | string) => `/enrollment-applications/${id}/approve`,
    reject: (id: number | string) => `/enrollment-applications/${id}/reject`,
  },
  classes: {
    list: '/classes',
    detail: (id: number | string) => `/classes/${id}`,
  },
  subjects: {
    list: '/subjects',
    detail: (id: number | string) => `/subjects/${id}`,
  },
  departments: {
    list: '/departments',
    detail: (id: number | string) => `/departments/${id}`,
  },
  gradeLevels: {
    list: '/grade-levels',
    detail: (id: number | string) => `/grade-levels/${id}`,
  },
  gradingScales: {
    list: '/grading-scales',
    detail: (id: number | string) => `/grading-scales/${id}`,
    getGrade: '/grading-scales/get-grade',
  },
  rooms: {
    list: '/rooms',
    detail: (id: number | string) => `/rooms/${id}`,
  },
  terms: {
    list: '/terms',
    current: '/terms/current',
    detail: (id: number | string) => `/terms/${id}`,
  },
  assignments: {
    list: '/assignments',
    detail: (id: number | string) => `/assignments/${id}`,
  },
  grades: {
    byClass: (classId: number | string) => `/grades/class/${classId}`,
    byStudent: (studentId: number | string) => `/grades/student/${studentId}`,
    store: '/grades',
    bulk: '/grades/bulk',
    classPerformance: (classId: number | string) => `/grades/class/${classId}/performance`,
  },
  exams: {
    list: '/exams',
    detail: (id: number | string) => `/exams/${id}`,
    analytics: '/exams/analytics/performance',
    approveResults: (id: number | string) => `/exams/${id}/results/approve`,
    publish: (id: number | string) => `/exams/${id}/publish`,
    recordResults: (id: number | string) => `/exams/${id}/results`,
  },
  tests: {
    list: '/tests',
    detail: (id: number | string) => `/tests/${id}`,
    recordResults: (id: number | string) => `/tests/${id}/results`,
  },
  attendance: {
    list: '/attendance',
    todaySummary: '/attendance/today/summary',
    studentSummary: (id: number | string) => `/attendance/student/${id}/summary`,
    classReport: (id: number | string) => `/attendance/class/${id}/report`,
  },
  timetable: {
    list: '/timetable',
    detail: (id: number | string) => `/timetable/${id}`,
    generate: '/timetable/generate',
    generateBulk: '/timetable/generate-bulk',
  },
  teacherAssignments: {
    list: '/teacher-assignments',
    detail: (id: number | string) => `/teacher-assignments/${id}`,
  },
  holidayPrograms: {
    list: '/holiday-programs',
    detail: (id: number | string) => `/holiday-programs/${id}`,
    enrollments: (id: number | string) => `/holiday-programs/${id}/enrollments`,
    enroll: (id: number | string) => `/holiday-programs/${id}/enroll`,
    attendance: (id: number | string) => `/holiday-programs/${id}/attendance`,
  },
  schoolTrips: {
    list: '/school-trips',
    detail: (id: number | string) => `/school-trips/${id}`,
    enrollments: (id: number | string) => `/school-trips/${id}/enrollments`,
    enroll: (id: number | string) => `/school-trips/${id}/enroll`,
  },
  finance: {
    summary: '/finance/summary',
    outstandingBalances: '/finance/outstanding-balances',
    aging: '/finance/aging',
    reconciliation: '/finance/reconciliation',
    cashFlow: '/finance/cash-flow',
    periodReport: (period: string) => `/finance/reports/${period}`,
  },
  payments: {
    list: '/payments',
    receipt: (id: number | string) => `/payments/${id}/receipt`,
    reverse: (id: number | string) => `/payments/${id}/reverse`,
    detail: (id: number | string) => `/payments/${id}`,
  },
  transactions: {
    list: '/transactions',
    summary: '/transactions/summary',
    create: '/transactions',
    detail: (id: number | string) => `/transactions/${id}`,
  },
  invoices: {
    list: '/invoices',
    detail: (id: number | string) => `/invoices/${id}`,
    print: (id: number | string) => `/invoices/${id}/print`,
  },
  feeStructures: {
    list: '/fee-structures',
    detail: (id: number | string) => `/fee-structures/${id}`,
  },
  feeCategories: {
    list: '/fee-categories',
    detail: (id: number | string) => `/fee-categories/${id}`,
  },
  feeGroups: {
    list: '/fee-groups',
    detail: (id: number | string) => `/fee-groups/${id}`,
  },
  feeDiscounts: {
    list: '/fee-discounts',
    detail: (id: number | string) => `/fee-discounts/${id}`,
  },
  incomeHeads: {
    list: '/income-heads',
    detail: (id: number | string) => `/income-heads/${id}`,
  },
  expenseHeads: {
    list: '/expense-heads',
    detail: (id: number | string) => `/expense-heads/${id}`,
  },
  leaveTypes: {
    list: '/leave-types',
    detail: (id: number | string) => `/leave-types/${id}`,
  },
  designations: {
    list: '/designations',
    detail: (id: number | string) => `/designations/${id}`,
  },
  employees: {
    list: '/employees',
    detail: (id: number | string) => `/employees/${id}`,
  },
  staffAttendance: {
    list: '/staff-attendance',
    roster: '/staff-attendance/roster',
    summary: '/staff-attendance/summary',
    store: '/staff-attendance',
  },
  studentCategories: {
    list: '/student-categories',
    detail: (id: number | string) => `/student-categories/${id}`,
  },
  certificateTemplates: {
    list: '/certificate-templates',
    detail: (id: number | string) => `/certificate-templates/${id}`,
    issue: (id: number | string) => `/certificate-templates/${id}/issue`,
  },
  schoolCertificates: {
    list: '/school-certificates',
    detail: (id: number | string) => `/school-certificates/${id}`,
    download: (id: number | string) => `/school-certificates/${id}/download`,
    revoke: (id: number | string) => `/school-certificates/${id}/revoke`,
    verify: (code: string) => `/certificates/verify/${encodeURIComponent(code)}`,
  },
  examSchedules: {
    list: '/exam-schedules',
    detail: (id: number | string) => `/exam-schedules/${id}`,
  },
  libraryMembers: {
    list: '/library/members',
    detail: (id: number | string) => `/library/members/${id}`,
  },
  schoolCurrencies: {
    list: '/school-currencies',
    detail: (id: number | string) => `/school-currencies/${id}`,
  },
  schoolLanguages: {
    list: '/school-languages',
    detail: (id: number | string) => `/school-languages/${id}`,
  },
  payroll: {
    list: '/payroll',
    teachers: '/payroll/teachers',
    summary: '/payroll/summary',
    trends: '/payroll/trends',
    departmentSummary: '/payroll/department-summary',
    teacherHistory: (id: number | string) => `/payroll/teachers/${id}/history`,
    payslip: (id: number | string) => `/payroll/${id}/payslip`,
    generate: '/payroll/generate',
    detail: (id: number | string) => `/payroll/${id}`,
    process: (id: number | string) => `/payroll/${id}/process`,
  },
  inventory: {
    items: '/inventory/items',
    item: (id: number | string) => `/inventory/items/${id}`,
    restock: (id: number | string) => `/inventory/items/${id}/restock`,
    sales: '/inventory/sales',
  },
  procurement: {
    requisitions: '/procurement/requisitions',
    submit: (id: number | string) => `/procurement/requisitions/${id}/submit`,
    disburse: (id: number | string) => `/procurement/requisitions/${id}/disburse`,
    vendors: '/procurement/vendors',
    goodsReceipts: '/procurement/goods-receipts',
  },
  assets: {
    list: '/assets',
    maintenance: (id: number | string) => `/assets/${id}/maintenance`,
    dispose: (id: number | string) => `/assets/${id}/dispose`,
  },
  transport: {
    vehicles: '/transport/vehicles',
    vehicle: (id: number | string) => `/transport/vehicles/${id}`,
    drivers: '/transport/drivers',
    driver: (id: number | string) => `/transport/drivers/${id}`,
    routes: '/transport/routes',
    route: (id: number | string) => `/transport/routes/${id}`,
    allocations: '/transport/allocations',
  },
  hostels: {
    list: '/hostels',
    rooms: (id: number | string) => `/hostels/${id}/rooms`,
    allocations: '/hostels/allocations',
  },
  library: {
    books: '/library/books',
    loans: '/library/loans',
    borrow: '/library/loans',
    return: (id: number | string) => `/library/loans/${id}/return`,
  },
  visitors: {
    list: '/visitors',
    checkIn: '/visitors/check-in',
    checkOut: (id: number | string) => `/visitors/${id}/check-out`,
  },
  helpDesk: {
    list: '/help-desk/tickets',
    detail: (id: number | string) => `/help-desk/tickets/${id}`,
    resolve: (id: number | string) => `/help-desk/tickets/${id}/resolve`,
    close: (id: number | string) => `/help-desk/tickets/${id}/close`,
  },
  recruitment: {
    jobs: '/recruitment/jobs',
    job: (id: number | string) => `/recruitment/jobs/${id}`,
    closeJob: (id: number | string) => `/recruitment/jobs/${id}/close`,
    applications: '/recruitment/applications',
    application: (id: number | string) => `/recruitment/applications/${id}`,
    shortlist: (id: number | string) => `/recruitment/applications/${id}/shortlist`,
    interview: (id: number | string) => `/recruitment/applications/${id}/interview`,
    offer: (id: number | string) => `/recruitment/applications/${id}/offer`,
    hire: (id: number | string) => `/recruitment/applications/${id}/hire`,
    reject: (id: number | string) => `/recruitment/applications/${id}/reject`,
  },
  health: {
    profile: (studentId: number | string) => `/health/students/${studentId}/profile`,
    visits: '/health/clinic-visits',
  },
  events: { list: '/events', detail: (id: number | string) => `/events/${id}` },
  discipline: {
    list: '/disciplinary-records',
    detail: (id: number | string) => `/disciplinary-records/${id}`,
  },
  communications: {
    threads: '/communications/threads',
    parents: '/communications/parents',
    thread: (id: number | string) => `/communications/threads/${id}`,
    reply: (id: number | string) => `/communications/threads/${id}/messages`,
  },
  announcements: {
    list: '/announcements',
    detail: (id: number | string) => `/announcements/${id}`,
  },
  leaveRequests: {
    list: '/leave-requests',
    approve: (id: number | string) => `/leave-requests/${id}/approve`,
    reject: (id: number | string) => `/leave-requests/${id}/reject`,
  },
  reports: {
    store: '/reports',
    templates: '/reports/templates',
    export: '/reports/export',
    academicPerformance: '/reports/academic-performance',
    attendance: '/reports/attendance',
    financial: '/reports/financial',
    classReport: (id: number | string) => `/reports/class/${id}`,
    generate: (type: string) => `/reports/${type}`,
  },
  analytics: { insights: '/analytics/insights' },
  workflows: {
    pending: '/workflows/pending',
    history: '/workflows/history',
    detail: (id: number | string) => `/workflows/${id}`,
    approve: (id: number | string) => `/workflows/${id}/approve`,
    reject: (id: number | string) => `/workflows/${id}/reject`,
  },
  compliance: {
    policies: '/compliance/policies',
    incidents: '/compliance/incidents',
  },
  consentForms: {
    list: '/consent-forms',
  },
  auditLogs: {
    list: '/audit-logs',
    loginHistory: '/audit-logs/login-history',
    detail: (id: number | string) => `/audit-logs/${id}`,
  },
  parentPortal: {
    dashboard: '/parent/portal/dashboard',
    children: '/parent/portal/children',
    results: (studentId: number | string) => `/parent/portal/students/${studentId}/results`,
    attendance: (studentId: number | string) => `/parent/portal/students/${studentId}/attendance`,
    fees: (studentId: number | string) => `/parent/portal/students/${studentId}/fees`,
    discipline: (studentId: number | string) => `/parent/portal/students/${studentId}/discipline`,
    progress: (studentId: number | string) => `/parent/portal/students/${studentId}/progress`,
    announcements: '/parent/portal/announcements',
    notifications: '/parent/portal/notifications',
    markNotificationRead: (id: number | string) => `/parent/portal/notifications/${id}/read`,
    markAllNotificationsRead: '/parent/portal/notifications/read-all',
    threads: '/parent/portal/communications/threads',
    threadMessages: (threadId: number | string) => `/parent/portal/communications/threads/${threadId}/messages`,
    consentForms: '/parent/portal/consent-forms',
    respondConsent: (id: number | string) => `/parent/portal/consent-forms/${id}/respond`,
    storeItems: '/parent/portal/store/items',
    storeBuy: '/parent/portal/store/buy',
    trips: '/parent/portal/trips',
    enrollTrip: (id: number | string) => `/parent/portal/trips/${id}/enroll`,
  },
  enterprise: {
    commandCenter: '/enterprise/command-center',
    academic: {
      calendar: '/enterprise/academic/calendar',
      curriculum: '/enterprise/academic/curriculum',
      assessmentCategories: '/enterprise/academic/assessment-categories',
      promotionRules: '/enterprise/academic/promotion-rules',
      gpaRanking: '/enterprise/academic/gpa-ranking',
    },
    finance: {
      accounts: '/enterprise/finance/accounts',
      seedAccounts: '/enterprise/finance/accounts/seed',
      journals: '/enterprise/finance/journals',
      exchangeRates: '/enterprise/finance/exchange-rates',
      instalmentPlans: '/enterprise/finance/instalment-plans',
      bankStatements: '/enterprise/finance/bank-statements',
      profitLoss: '/enterprise/finance/reports/profit-loss',
      balanceSheet: '/enterprise/finance/reports/balance-sheet',
      cashflowForecast: '/enterprise/finance/cashflow-forecast',
      revenueRules: '/enterprise/finance/revenue-rules',
    },
    exams: {
      questionBank: '/enterprise/exams/question-bank',
      generatePaper: '/enterprise/exams/generate-paper',
      startCbt: '/enterprise/exams/cbt/start',
      submitCbt: (id: number | string) => `/enterprise/exams/cbt/${id}/submit`,
      remarkRequests: '/enterprise/exams/remark-requests',
      delegations: '/enterprise/workflows/delegations',
    },
    hr: {
      performanceReviews: '/enterprise/hr/performance-reviews',
      contracts: '/enterprise/hr/contracts',
      certifications: '/enterprise/hr/certifications',
    },
    intelligence: {
      earlyWarnings: '/enterprise/early-warnings',
      alumni: '/enterprise/alumni',
      campaigns: '/enterprise/campaigns',
    },
  },
  platform: {
    policyRules: '/platform/policy-rules',
    workflowDefinitions: '/platform/workflow-definitions',
    branchTree: '/platform/branches/tree',
    retentionPolicies: '/platform/retention-policies',
    maskingRules: '/platform/masking-rules',
    documents: '/platform/documents',
    signDocument: (id: number | string) => `/platform/documents/${id}/sign`,
    certificates: '/platform/certificates',
    vault: '/platform/vault',
    scholarships: '/platform/scholarships',
    paymentGateways: '/platform/payment-gateways',
    initiatePayment: '/platform/payments/initiate',
    paymentStatus: (reference: string) => `/platform/payments/status/${reference}`,
    refunds: '/platform/refunds',
    behaviorPoints: '/platform/behavior-points',
    interventions: '/platform/interventions',
    staffTasks: '/platform/staff-tasks',
    staffTask: (id: number | string) => `/platform/staff-tasks/${id}`,
    staffFeed: '/platform/staff-feed',
    operationsLive: '/platform/operations/live',
    resolveAlert: (id: number | string) => `/platform/operations/alerts/${id}/resolve`,
    predictiveAnalytics: '/platform/analytics/predictive',
    systemHealth: '/platform/system/health',
    auditIntegrity: '/platform/audit-integrity/verify',
    apiClients: '/platform/api-clients',
    communications: {
      send: '/platform/communications/send',
      tracking: '/platform/communications/tracking',
      markRead: (id: number | string) => `/platform/communications/deliveries/${id}/read`,
    },
  },
} as const
