<?php

return [
    [
        'id' => 1,
        'name' => 'View Users',
        'slug' => 'users.view',
        'resource' => 'users',
        'action' => 'view',
        'description' => 'View user list and details',
    ],
    [
        'id' => 2,
        'name' => 'Create Users',
        'slug' => 'users.create',
        'resource' => 'users',
        'action' => 'create',
        'description' => 'Create new users',
    ],
    [
        'id' => 3,
        'name' => 'Edit Users',
        'slug' => 'users.edit',
        'resource' => 'users',
        'action' => 'edit',
        'description' => 'Edit user information',
    ],
    [
        'id' => 4,
        'name' => 'Delete Users',
        'slug' => 'users.delete',
        'resource' => 'users',
        'action' => 'delete',
        'description' => 'Delete users',
    ],
    [
        'id' => 5,
        'name' => 'View Reports',
        'slug' => 'reports.view',
        'resource' => 'reports',
        'action' => 'view',
        'description' => 'View reports and analytics',
    ],
    [
        'id' => 6,
        'name' => 'Generate Reports',
        'slug' => 'reports.generate',
        'resource' => 'reports',
        'action' => 'generate',
        'description' => 'Generate and export reports',
    ],
    [
        'id' => 7,
        'name' => 'Manage Roles',
        'slug' => 'roles.manage',
        'resource' => 'roles',
        'action' => 'manage',
        'description' => 'Manage roles and permission groups',
    ],
    [
        'id' => 8,
        'name' => 'View Transactions',
        'slug' => 'transactions.view',
        'resource' => 'transactions',
        'action' => 'view',
        'description' => 'View transaction history',
    ],
    [
        'id' => 9,
        'name' => 'Manage Settings',
        'slug' => 'settings.manage',
        'resource' => 'settings',
        'action' => 'manage',
        'description' => 'Manage school and system settings',
    ],
    [
        'id' => 10,
        'name' => 'View Dashboard',
        'slug' => 'dashboard.view',
        'resource' => 'dashboard',
        'action' => 'view',
        'description' => 'View staff dashboard',
    ],
    [
        'id' => 11,
        'name' => 'View Audit Logs',
        'slug' => 'audit.view',
        'resource' => 'audit',
        'action' => 'view',
        'description' => 'View audit trail and sign-in history',
    ],
    [
        'id' => 12,
        'name' => 'Manage Students',
        'slug' => 'students.manage',
        'resource' => 'students',
        'action' => 'manage',
        'description' => 'Create, edit, and manage student records',
    ],
    [
        'id' => 13,
        'name' => 'Manage Enrollment',
        'slug' => 'enrollment.manage',
        'resource' => 'enrollment',
        'action' => 'manage',
        'description' => 'Review and process enrollment applications',
    ],
    [
        'id' => 14,
        'name' => 'Manage Academics',
        'slug' => 'academics.manage',
        'resource' => 'academics',
        'action' => 'manage',
        'description' => 'Classes, subjects, terms, and timetable setup',
    ],
    [
        'id' => 15,
        'name' => 'Manage Attendance',
        'slug' => 'attendance.manage',
        'resource' => 'attendance',
        'action' => 'manage',
        'description' => 'Take and review attendance registers',
    ],
    [
        'id' => 16,
        'name' => 'Manage Examinations',
        'slug' => 'exams.manage',
        'resource' => 'exams',
        'action' => 'manage',
        'description' => 'Exams, marks, approval, and publication',
    ],
    [
        'id' => 17,
        'name' => 'Manage Finance',
        'slug' => 'finance.manage',
        'resource' => 'finance',
        'action' => 'manage',
        'description' => 'Payments, invoices, fees, and payroll',
    ],
    [
        'id' => 18,
        'name' => 'Manage HR',
        'slug' => 'hr.manage',
        'resource' => 'hr',
        'action' => 'manage',
        'description' => 'Leave, discipline, and staff HR workflows',
    ],
    [
        'id' => 19,
        'name' => 'Manage Communications',
        'slug' => 'communications.manage',
        'resource' => 'communications',
        'action' => 'manage',
        'description' => 'Announcements and messaging',
    ],
    [
        'id' => 20,
        'name' => 'Manage Operations',
        'slug' => 'operations.manage',
        'resource' => 'operations',
        'action' => 'manage',
        'description' => 'Full campus operations (library, transport, inventory, reception)',
    ],
    [
        'id' => 21,
        'name' => 'Manage Compliance',
        'slug' => 'compliance.manage',
        'resource' => 'compliance',
        'action' => 'manage',
        'description' => 'Policies, incidents, and consent forms',
    ],
    [
        'id' => 22,
        'name' => 'Enter Exam Results',
        'slug' => 'exams.enter_results',
        'resource' => 'exams',
        'action' => 'enter_results',
        'description' => 'Enter marks for assigned subjects only',
    ],
    [
        'id' => 23,
        'name' => 'Manage Library',
        'slug' => 'library.manage',
        'resource' => 'library',
        'action' => 'manage',
        'description' => 'Library catalogue, loans, and returns',
    ],
    [
        'id' => 24,
        'name' => 'Manage Transport',
        'slug' => 'transport.manage',
        'resource' => 'transport',
        'action' => 'manage',
        'description' => 'Vehicles, drivers, routes, and student allocations',
    ],
    [
        'id' => 25,
        'name' => 'Manage Inventory',
        'slug' => 'inventory.manage',
        'resource' => 'inventory',
        'action' => 'manage',
        'description' => 'School store, stock, and sales',
    ],
    [
        'id' => 26,
        'name' => 'Manage Reception',
        'slug' => 'reception.manage',
        'resource' => 'reception',
        'action' => 'manage',
        'description' => 'Visitor check-in and front-desk reception',
    ],
    [
        'id' => 27,
        'name' => 'Manage Health Clinic',
        'slug' => 'health.manage',
        'resource' => 'health',
        'action' => 'manage',
        'description' => 'Clinic visits and student health records',
    ],
    [
        'id' => 28,
        'name' => 'Manage Hostels',
        'slug' => 'hostel.manage',
        'resource' => 'hostel',
        'action' => 'manage',
        'description' => 'Boarding houses and room assignments',
    ],
];
