import {
  ArrowLeftRight,
  Banknote,
  BookOpen,
  CreditCard,
  HardDrive,
  Layers,
  LineChart,
  Percent,
  PiggyBank,
  Receipt,
  Scale,
  ShoppingCart,
  Tags,
  TrendingDown,
  TrendingUp,
  Wallet,
} from '@lucide/vue'
import type { ModuleHubTab } from '@/lib/module-hub'

export const FINANCE_HUB_TABS: ModuleHubTab[] = [
  {
    id: 'overview',
    title: 'Overview',
    description: 'Collections, cash movement, and the numbers that matter today.',
    icon: Wallet,
    panel: 'finance-overview',
    group: 'Home',
  },
  {
    id: 'payments',
    title: 'Payments',
    description: 'Record and review fee collections.',
    icon: CreditCard,
    listKey: 'finance-payments',
    group: 'Fees',
  },
  {
    id: 'invoices',
    title: 'Invoices',
    description: 'Bill students and track outstanding balances.',
    icon: Receipt,
    listKey: 'finance-invoices',
    group: 'Fees',
  },
  {
    id: 'fee-categories',
    title: 'Fee categories',
    description: 'Group fee types used on invoices and structures.',
    icon: Tags,
    listKey: 'finance-fee-categories',
    group: 'Fees',
  },
  {
    id: 'fee-groups',
    title: 'Fee groups',
    description: 'Bundle categories for packaging on invoices.',
    icon: Layers,
    listKey: 'finance-fee-groups',
    group: 'Fees',
  },
  {
    id: 'fee-discounts',
    title: 'Fee discounts',
    description: 'Percent or fixed discounts by category.',
    icon: Percent,
    listKey: 'finance-fee-discounts',
    group: 'Fees',
  },
  {
    id: 'fee-structures',
    title: 'Fee structures',
    description: 'Configure amounts by class and term.',
    icon: Tags,
    listKey: 'finance-fees',
    group: 'Fees',
  },
  {
    id: 'income-heads',
    title: 'Income heads',
    description: 'Classify fee payments and other money coming in.',
    icon: BookOpen,
    listKey: 'finance-income-heads',
    group: 'Accounts',
  },
  {
    id: 'expense-heads',
    title: 'Expense heads',
    description: 'Classify school spending for reporting.',
    icon: BookOpen,
    listKey: 'finance-expense-heads',
    group: 'Accounts',
  },
  {
    id: 'budgets',
    title: 'Budgets',
    description: 'Plan department spend, approve budgets, and track utilisation.',
    icon: PiggyBank,
    listKey: 'finance-budgets',
    group: 'Accounts',
  },
  {
    id: 'income',
    title: 'Income',
    description: 'Record manual income entries classified by income head.',
    icon: TrendingUp,
    listKey: 'finance-income',
    group: 'Accounts',
  },
  {
    id: 'expense',
    title: 'Expense',
    description: 'Record manual expense entries classified by expense head.',
    icon: TrendingDown,
    listKey: 'finance-expense',
    group: 'Accounts',
  },
  {
    id: 'transactions',
    title: 'Transactions',
    description: 'Full ledger — money in and out across currencies.',
    icon: ArrowLeftRight,
    component: () => import('@/modules/finance/views/TransactionsManagementView.vue'),
    group: 'Accounts',
  },
  {
    id: 'payroll',
    title: 'Payroll',
    description: 'Generate payslips and pay staff.',
    icon: Banknote,
    component: () => import('@/modules/finance/views/PayrollManagementView.vue'),
    group: 'Payroll & cash',
  },
  {
    id: 'cash-flow',
    title: 'Cash flow',
    description: 'Money in vs money out so everything balances.',
    icon: Scale,
    component: () => import('@/modules/finance/views/FinanceCashFlowView.vue'),
    group: 'Payroll & cash',
  },
  {
    id: 'aging',
    title: 'Aging',
    description: 'Outstanding balances by due date.',
    icon: LineChart,
    component: () => import('@/modules/finance/views/FinanceReportsView.vue'),
    group: 'Payroll & cash',
  },
  {
    id: 'procurement',
    title: 'Spend',
    description: 'Spend requests and vendor payments.',
    icon: ShoppingCart,
    group: 'Operations',
    sections: [
      {
        listKey: 'ops-procurement',
        title: 'Spend requests',
        description: 'Request → approve → record payment.',
      },
      {
        listKey: 'ops-procurement-vendors',
        title: 'Vendors',
        description: 'Supplier records for procurement.',
      },
    ],
  },
  {
    id: 'assets',
    title: 'Assets',
    description: 'School assets and depreciation records.',
    icon: HardDrive,
    listKey: 'ops-assets',
    group: 'Operations',
  },
]

export const FINANCE_HUB_DEFAULT_TAB = 'overview'
