<?php

namespace App\Services\Ai;

use App\Contracts\TeachingAssistant;

/**
 * Deterministic, template-based teaching assistant used until a real LLM
 * provider is configured. Produces useful scaffolding a teacher can edit.
 */
class StubTeachingAssistant implements TeachingAssistant
{
    public function isLive(): bool
    {
        return false;
    }

    public function generate(string $task, array $context = []): array
    {
        $subject = (string) ($context['subject'] ?? 'the subject');
        $topic = (string) ($context['topic'] ?? 'the topic');
        $grade = (string) ($context['grade'] ?? $context['class'] ?? 'the class');
        $count = (int) ($context['count'] ?? 5);

        [$title, $content] = match ($task) {
            'lesson_plan' => [
                "Lesson plan: {$topic}",
                $this->lessonPlan($subject, $topic, $grade),
            ],
            'quiz' => [
                "Quiz: {$topic}",
                $this->quiz($topic, $count),
            ],
            'exam_paper' => [
                "Exam paper: {$subject}",
                $this->examPaper($subject, $topic, $count),
            ],
            'marking_guide' => [
                "Marking guide: {$topic}",
                $this->markingGuide($topic, $count),
            ],
            'teaching_activities' => [
                "Teaching activities: {$topic}",
                $this->activities($topic),
            ],
            'class_analysis' => [
                "Class performance analysis",
                $this->classAnalysis($context),
            ],
            'interventions' => [
                "Recommended interventions",
                $this->interventions($context),
            ],
            'student_comment' => [
                'Student report comment',
                $this->studentComment($context),
            ],
            'progress_summary' => [
                'Learner progress summary',
                $this->progressSummary($context),
            ],
            default => [
                'Teaching content',
                "Draft content for \"{$task}\". Provide more context (subject, topic, class) for a richer result.",
            ],
        };

        return [
            'task' => $task,
            'title' => $title,
            'content' => $content,
            'meta' => [
                'provider' => 'stub',
                'live' => false,
                'note' => 'Generated by the built-in template engine. Connect an AI provider for tailored output.',
            ],
        ];
    }

    private function lessonPlan(string $subject, string $topic, string $grade): string
    {
        return implode("\n", [
            "Subject: {$subject}    Class: {$grade}    Topic: {$topic}",
            '',
            'Learning objectives:',
            "- Define and explain the key concepts of {$topic}.",
            "- Apply {$topic} to solve practical problems.",
            "- Evaluate outcomes and reflect on {$topic}.",
            '',
            'Learning outcomes:',
            "- Learners can describe {$topic} in their own words.",
            '- Learners can complete guided and independent tasks.',
            '',
            'Teaching activities:',
            '1. Starter (5 min): recap prior knowledge with a quick question.',
            '2. Introduction (10 min): present the concept with examples.',
            '3. Guided practice (15 min): worked examples as a class.',
            '4. Independent practice (15 min): learners attempt tasks.',
            '5. Plenary (5 min): review answers and address misconceptions.',
            '',
            'Required resources: whiteboard, worksheets, textbook.',
            'Assessment: exit ticket / short quiz.',
        ]);
    }

    private function quiz(string $topic, int $count): string
    {
        $lines = ["Quiz on {$topic} ({$count} questions):", ''];
        for ($i = 1; $i <= max(1, $count); $i++) {
            $lines[] = "{$i}. Question {$i} about {$topic}? ____________________";
        }

        return implode("\n", $lines);
    }

    private function examPaper(string $subject, string $topic, int $count): string
    {
        $lines = ["{$subject} examination", "Section A: {$topic}", ''];
        for ($i = 1; $i <= max(1, $count); $i++) {
            $lines[] = "Q{$i}. [".(2 * $i)." marks] Question {$i} on {$topic}.";
        }
        $lines[] = '';
        $lines[] = 'Total: '.array_sum(range(2, 2 * max(1, $count), 2)).' marks';

        return implode("\n", $lines);
    }

    private function markingGuide(string $topic, int $count): string
    {
        $lines = ["Marking guide: {$topic}", ''];
        for ($i = 1; $i <= max(1, $count); $i++) {
            $lines[] = "Q{$i}: Award marks for correct method and final answer. Key point(s) expected.";
        }

        return implode("\n", $lines);
    }

    private function activities(string $topic): string
    {
        return implode("\n", [
            "Suggested activities for {$topic}:",
            '- Think-pair-share discussion.',
            '- Small-group problem solving with mini-whiteboards.',
            '- Real-world application task.',
            '- Peer-marking of a short exercise.',
            '- Exit ticket to check understanding.',
        ]);
    }

    private function classAnalysis(array $context): string
    {
        $avg = $context['average'] ?? 'N/A';

        return implode("\n", [
            "Class average: {$avg}.",
            'Strengths: most learners grasp core concepts.',
            'Focus areas: reinforce application and exam technique.',
            'Suggested next step: targeted revision of weak topics.',
        ]);
    }

    private function interventions(array $context): string
    {
        $name = $context['student_name'] ?? 'the learner';

        return implode("\n", [
            "Recommended interventions for {$name}:",
            '- Schedule a short one-on-one check-in.',
            '- Provide extra practice on weak topics.',
            '- Recommend an after-class support session.',
            '- Involve the guardian for home support.',
        ]);
    }

    private function studentComment(array $context): string
    {
        $name = $context['student_name'] ?? 'This learner';

        return "{$name} has made steady progress this term. They engage well in class and should continue "
            .'practising independently to build confidence and consolidate understanding.';
    }

    private function progressSummary(array $context): string
    {
        $name = $context['student_name'] ?? 'The learner';

        return "{$name}'s progress is on track. Attendance and participation are satisfactory. "
            .'Continued focus on weaker topics will support further improvement.';
    }
}
