import {
  Bell,
  BookOpen,
  Bot,
  CalendarDays,
  ClipboardCheck,
  Download,
  FileText,
  GraduationCap,
  Layers,
  NotebookPen,
  Palmtree,
  ShieldAlert,
  Users,
  Video,
  FolderOpen,
  Building2,
  UserRoundCog,
} from '@lucide/vue'
import type { ModuleHubTab } from '@/lib/module-hub'

export const TEACHING_HUB_TABS: ModuleHubTab[] = [
  {
    id: 'classes',
    title: 'My Classes',
    description: 'Assigned classes, students, and learner history.',
    icon: Users,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/MyClassesPanel.vue'),
  },
  {
    id: 'lessons',
    title: 'Lesson plans',
    description: 'Create, copy, submit, and complete lesson plans.',
    icon: NotebookPen,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/LessonPlansPanel.vue'),
  },
  {
    id: 'syllabus',
    title: 'Syllabus',
    description: 'Topics, chapters, and syllabus coverage.',
    icon: Layers,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/SyllabusPanel.vue'),
  },
  {
    id: 'resources',
    title: 'Resources',
    description: 'Notes, worksheets, videos, and shared materials.',
    icon: FolderOpen,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/ResourcesPanel.vue'),
  },
  {
    id: 'lms',
    title: 'Online learning',
    description: 'Virtual lessons, recordings, quizzes, and polls.',
    icon: Video,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/OnlineLearningPanel.vue'),
  },
  {
    id: 'homework',
    title: 'Homework',
    description: 'Submissions, grading, and return workflow.',
    icon: BookOpen,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/HomeworkPanel.vue'),
  },
  {
    id: 'report-cards',
    title: 'Report cards',
    description: 'Narrative comments, strengths, and recommendations.',
    icon: FileText,
    capability: 'canEnterExamResults',
    component: () => import('@/modules/teaching/views/ReportCardsPanel.vue'),
  },
  {
    id: 'behaviour',
    title: 'Behaviour',
    description: 'Points, rewards, misconduct, and support plans.',
    icon: ShieldAlert,
    capability: 'canManageStudents',
    component: () => import('@/modules/teaching/views/BehaviourSupportPanel.vue'),
  },
  {
    id: 'calendar',
    title: 'Calendar',
    description: 'School events, exams, and assignment deadlines.',
    icon: CalendarDays,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TeacherCalendarPanel.vue'),
  },
  {
    id: 'timetable-tools',
    title: 'Timetable tools',
    description: 'Free periods, exam timetable, and change requests.',
    icon: ClipboardCheck,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TimetableToolsPanel.vue'),
  },
  {
    id: 'leave',
    title: 'Leave',
    description: 'Apply for leave and track approval status.',
    icon: Palmtree,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TeacherLeavePanel.vue'),
  },
  {
    id: 'cover',
    title: 'Cover classes',
    description: 'Substitution / relief class requests.',
    icon: UserRoundCog,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/SubstitutionsPanel.vue'),
  },
  {
    id: 'department',
    title: 'Department',
    description: 'Department peers and shared teaching resources.',
    icon: Building2,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/DepartmentPanel.vue'),
  },
  {
    id: 'exports',
    title: 'Export & print',
    description: 'Registers, class lists, mark sheets, and reports.',
    icon: Download,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/ExportPanel.vue'),
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'Reminders, submissions, and school announcements.',
    icon: Bell,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TeacherNotificationsPanel.vue'),
  },
  {
    id: 'ai',
    title: 'AI assistant',
    description: 'Generate lesson plans, quizzes, comments, and more.',
    icon: Bot,
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/AiTeachingPanel.vue'),
  },
  {
    id: 'assessments',
    title: 'Participation',
    description: 'Class participation and continuous assessment notes.',
    icon: GraduationCap,
    capability: 'canEnterExamResults',
    component: () => import('@/modules/teaching/views/ParticipationPanel.vue'),
  },
]

export const TEACHING_HUB_DEFAULT_TAB = 'classes'
