import {
  Bell,
  BookOpen,
  Bot,
  CalendarDays,
  ClipboardCheck,
  Download,
  FileText,
  GraduationCap,
  Layers,
  NotebookPen,
  Palmtree,
  ShieldAlert,
  Users,
  Video,
  FolderOpen,
  Building2,
  UserRoundCog,
} from '@lucide/vue'
import type { ModuleHubTab } from '@/lib/module-hub'

/**
 * Teaching workspace navigation.
 * Primary = daily teaching jobs. Secondary = useful but less frequent (More).
 */
export const TEACHING_HUB_TABS: ModuleHubTab[] = [
  {
    id: 'classes',
    title: 'Classes',
    description: 'Pick a class, then mark, teach, or review learners.',
    icon: Users,
    priority: 'primary',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/MyClassesPanel.vue'),
  },
  {
    id: 'lessons',
    title: 'Lessons',
    description: 'Create, copy, submit, and complete lesson plans.',
    icon: NotebookPen,
    priority: 'primary',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/LessonPlansPanel.vue'),
  },
  {
    id: 'homework',
    title: 'Homework',
    description: 'Submissions, grading, and return workflow.',
    icon: BookOpen,
    priority: 'primary',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/HomeworkPanel.vue'),
  },
  {
    id: 'lms',
    title: 'Online learning',
    description: 'Virtual lessons, recordings, quizzes, and polls.',
    icon: Video,
    priority: 'primary',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/OnlineLearningPanel.vue'),
  },
  {
    id: 'behaviour',
    title: 'Behaviour',
    description: 'Points, rewards, misconduct, and support plans.',
    icon: ShieldAlert,
    priority: 'primary',
    capability: 'canManageStudents',
    component: () => import('@/modules/teaching/views/BehaviourSupportPanel.vue'),
  },
  {
    id: 'resources',
    title: 'Resources',
    description: 'Notes, worksheets, videos, and shared materials.',
    icon: FolderOpen,
    priority: 'secondary',
    group: 'Materials',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/ResourcesPanel.vue'),
  },
  {
    id: 'syllabus',
    title: 'Syllabus',
    description: 'Topics, chapters, and syllabus coverage.',
    icon: Layers,
    priority: 'secondary',
    group: 'Materials',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/SyllabusPanel.vue'),
  },
  {
    id: 'report-cards',
    title: 'Report cards',
    description: 'Narrative comments, strengths, and recommendations.',
    icon: FileText,
    priority: 'secondary',
    group: 'Assessment',
    capability: 'canEnterExamResults',
    component: () => import('@/modules/teaching/views/ReportCardsPanel.vue'),
  },
  {
    id: 'assessments',
    title: 'Participation',
    description: 'Class participation and continuous assessment notes.',
    icon: GraduationCap,
    priority: 'secondary',
    group: 'Assessment',
    capability: 'canEnterExamResults',
    component: () => import('@/modules/teaching/views/ParticipationPanel.vue'),
  },
  {
    id: 'calendar',
    title: 'Calendar',
    description: 'School events, exams, and assignment deadlines.',
    icon: CalendarDays,
    priority: 'secondary',
    group: 'Schedule',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TeacherCalendarPanel.vue'),
  },
  {
    id: 'timetable-tools',
    title: 'Timetable tools',
    description: 'Free periods, exam timetable, and change requests.',
    icon: ClipboardCheck,
    priority: 'secondary',
    group: 'Schedule',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TimetableToolsPanel.vue'),
  },
  {
    id: 'leave',
    title: 'Leave',
    description: 'Apply for leave and track approval status.',
    icon: Palmtree,
    priority: 'secondary',
    group: 'Staff',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TeacherLeavePanel.vue'),
  },
  {
    id: 'cover',
    title: 'Cover',
    description: 'Substitution and relief class requests.',
    icon: UserRoundCog,
    priority: 'secondary',
    group: 'Staff',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/SubstitutionsPanel.vue'),
  },
  {
    id: 'department',
    title: 'Department',
    description: 'Department peers and shared teaching resources.',
    icon: Building2,
    priority: 'secondary',
    group: 'Staff',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/DepartmentPanel.vue'),
  },
  {
    id: 'exports',
    title: 'Export',
    description: 'Registers, class lists, mark sheets, and reports.',
    icon: Download,
    priority: 'secondary',
    group: 'Utilities',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/ExportPanel.vue'),
  },
  {
    id: 'notifications',
    title: 'Alerts',
    description: 'Reminders, submissions, and school announcements.',
    icon: Bell,
    priority: 'secondary',
    group: 'Utilities',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/TeacherNotificationsPanel.vue'),
  },
  {
    id: 'ai',
    title: 'AI assist',
    description: 'Generate lesson plans, quizzes, comments, and more.',
    icon: Bot,
    priority: 'secondary',
    group: 'Utilities',
    capability: 'isStaff',
    component: () => import('@/modules/teaching/views/AiTeachingPanel.vue'),
  },
]

export const TEACHING_HUB_DEFAULT_TAB = 'classes'
