import {
  BadgeCheck,
  Briefcase,
  ClipboardCheck,
  FileCheck,
  IdCard,
  ListTodo,
  Palmtree,
  Scale,
  ScrollText,
  ShieldAlert,
  TriangleAlert,
  Users,
} from '@lucide/vue'
import type { ModuleHubTab } from '@/lib/module-hub'

export const HR_HUB_TABS: ModuleHubTab[] = [
  {
    id: 'employees',
    title: 'Employees',
    description: 'Non-teaching staff records and employment details.',
    icon: Users,
    capability: 'canManageTeachers',
    listKey: 'hr-employees',
  },
  {
    id: 'staff-tasks',
    title: 'Staff tasks',
    description: 'Assign and track operational work for school staff.',
    icon: ListTodo,
    capability: 'canManageTeachers',
    component: () => import('@/modules/hr/views/SchoolStaffTasksView.vue'),
  },
  {
    id: 'designations',
    title: 'Designations',
    description: 'Job titles used across teaching and support staff.',
    icon: IdCard,
    capability: 'canManageTeachers',
    listKey: 'hr-designations',
  },
  {
    id: 'leave',
    title: 'Leave',
    description: 'Staff leave requests and approvals.',
    icon: Palmtree,
    capability: 'canManageTeachers',
    component: () => import('@/modules/hr/views/LeaveRequestsView.vue'),
  },
  {
    id: 'leave-types',
    title: 'Leave types',
    description: 'Paid and unpaid leave categories with day allowances.',
    icon: BadgeCheck,
    capability: 'canManageTeachers',
    listKey: 'hr-leave-types',
  },
  {
    id: 'recruitment',
    title: 'Recruitment',
    description: 'Job postings and applicant pipeline.',
    icon: Briefcase,
    capability: 'canManageTeachers',
    sections: [
      {
        listKey: 'hr-recruitment-jobs',
        title: 'Job postings',
        description: 'Open roles and hiring campaigns.',
      },
      {
        listKey: 'hr-recruitment-applications',
        title: 'Applications',
        description: 'Track applicants from submission to hire.',
      },
    ],
  },
  {
    id: 'staff-attendance',
    title: 'Staff attendance',
    description: 'Daily attendance for teachers and employees.',
    icon: ClipboardCheck,
    capability: 'canManageTeachers',
    component: () => import('@/modules/hr/views/StaffAttendanceView.vue'),
  },
  {
    id: 'discipline',
    title: 'Discipline',
    description: 'Student discipline records and follow-up.',
    icon: ShieldAlert,
    capability: 'canManageStudents',
    listKey: 'hr-discipline',
  },
  {
    id: 'policies',
    title: 'Policies',
    description: 'School policies and compliance documents.',
    icon: Scale,
    capability: 'canManageTeachers',
    listKey: 'compliance',
  },
  {
    id: 'incidents',
    title: 'Incidents',
    description: 'Compliance incidents and follow-up.',
    icon: TriangleAlert,
    capability: 'canManageTeachers',
    listKey: 'compliance-incidents',
  },
  {
    id: 'consent',
    title: 'Consent',
    description: 'Consent forms for students and guardians.',
    icon: FileCheck,
    // School-wide consent admin — not class teachers.
    capability: 'canManageTeachers',
    listKey: 'compliance-consent',
  },
  {
    id: 'audit',
    title: 'Audit trail',
    description: 'Activity log and login history.',
    icon: ScrollText,
    capability: 'canViewAuditLogs',
    component: () => import('@/modules/compliance/views/AuditTrailView.vue'),
  },
]

export const HR_HUB_DEFAULT_TAB = 'employees'
